In [ ]:
# general imports
import pandas as pd
import os
import json

In [ ]:
# Optional environment setup.
# Set these before initializing vLLM, PyTorch, sentence-transformers, or transformers models.

# Restrict this notebook process to specific GPUs.
# Examples: "0" for one GPU, "0,1" for two GPUs.
# os.environ["CUDA_VISIBLE_DEVICES"] = "0"

# Optional: set for higher Hugging Face Hub rate limits and faster first-time downloads.
# os.environ["HF_TOKEN"] = "hf_..."

# MMAI Examples

## 1. Trial summarization walkthrough

### Read in data

In [2]:
trials_path = "data/scheduled__2025-09-04T230000+0000.trials_for_summarize.csv"
trials = pd.read_csv(trials_path)

### Local mode

`summarize_trials(...)` uses the local in-memory vLLM backend by default. Run this cell if you want local mode.

In [ ]:
from matchminer_ai.trials import summarize_trials

trial_results, metadata, qc_report = summarize_trials(
    trials, return_metadata=True, return_qc=True
)

# Optional: clear the cached local vLLM engine if GPU memory is tight.
# from matchminer_ai.llm.backends import clear_local_llm_cache
# clear_local_llm_cache()

/home/sabrina/mmai-package/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

INFO 05-18 19:17:17 [utils.py:233] non-default args: {'max_model_len': 10000, 'gpu_memory_utilization': 0.9, 'disable_log_stats': True, 'model': 'openai/gpt-oss-120b'}
INFO 05-18 19:17:18 [model.py:555] Resolved architecture: GptOssForCausalLM

Parse safetensors files: 100%|██████████| 15/15 [00:00<00:00, 100.50it/s]

INFO 05-18 19:17:18 [model.py:1680] Using max model len 10000

INFO 05-18 19:17:19 [nixl_utils.py:20] Setting UCX_RCACHE_MAX_UNRELEASED to '1024' to avoid a rare memory leak in UCX when using NIXL.
WARNING 05-18 19:17:19 [nixl_utils.py:34] NIXL is not available
WARNING 05-18 19:17:19 [nixl_utils.py:44] NIXL agent config is not available
INFO 05-18 19:17:20 [scheduler.py:239] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 05-18 19:17:20 [config.py:170] Overriding max cuda graph capture size to 1024 for performance.
INFO 05-18 19:17:20 [vllm.py:840] Asynchronous scheduling is enabled.
INFO 05-18 19:17:20 [kernel.py:205] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'])
(EngineCore pid=38281) INFO 05-18 19:17:23 [core.py:109] Initializing a V1 LLM engine (v0.20.2) with config: model='openai/gpt-oss-120b', speculative_config=None, tokenizer='openai/gpt-oss-120b', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=10000, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=gpt_oss_mxfp4, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='openai_gptoss', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=openai/gpt-oss-120b, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto')
(EngineCore pid=38281) INFO 05-18 19:17:24 [parallel_state.py:1402] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.128.0.42:47951 backend=nccl
(EngineCore pid=38281) INFO 05-18 19:17:24 [parallel_state.py:1715] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank 0, EPLB rank N/A
(EngineCore pid=38281) INFO 05-18 19:17:25 [gpu_model_runner.py:4777] Starting to load model openai/gpt-oss-120b...
(EngineCore pid=38281) INFO 05-18 19:17:26 [cuda.py:368] Using TRITON_ATTN attention backend out of potential backends: ['TRITON_ATTN'].
(EngineCore pid=38281) INFO 05-18 19:17:26 [mxfp4.py:401] Using 'MARLIN' Mxfp4 MoE backend.
(EngineCore pid=38281) INFO 05-18 19:17:27 [weight_utils.py:904] Filesystem type for checkpoints: EXT4. Checkpoint size: 60.77 GiB. Available RAM: 160.31 GiB.
(EngineCore pid=38281) INFO 05-18 19:17:27 [weight_utils.py:927] Auto-prefetch is disabled because the filesystem (EXT4) is not a recognized network FS (NFS/Lustre). If you want to force prefetching, start vLLM with --safetensors-load-strategy=prefetch.

Loading safetensors checkpoint shards:   0% Completed | 0/15 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   7% Completed | 1/15 [00:01<00:16,  1.20s/it]
Loading safetensors checkpoint shards:  13% Completed | 2/15 [00:02<00:14,  1.13s/it]
Loading safetensors checkpoint shards:  20% Completed | 3/15 [00:03<00:13,  1.15s/it]
Loading safetensors checkpoint shards:  27% Completed | 4/15 [00:04<00:12,  1.13s/it]
Loading safetensors checkpoint shards:  33% Completed | 5/15 [00:05<00:11,  1.15s/it]
Loading safetensors checkpoint shards:  40% Completed | 6/15 [00:06<00:10,  1.13s/it]
Loading safetensors checkpoint shards:  47% Completed | 7/15 [00:08<00:09,  1.15s/it]
Loading safetensors checkpoint shards:  53% Completed | 8/15 [00:09<00:07,  1.12s/it]
Loading safetensors checkpoint shards:  60% Completed | 9/15 [00:10<00:06,  1.15s/it]
Loading safetensors checkpoint shards:  67% Completed | 10/15 [00:11<00:05,  1.13s/it]
Loading safetensors checkpoint shards:  73% Completed | 11/15 [00:12<00:04,  1.15s/it]
Loading safetensors checkpoint shards:  80% Completed | 12/15 [00:13<00:03,  1.13s/it]
Loading safetensors checkpoint shards:  87% Completed | 13/15 [00:14<00:02,  1.10s/it]
Loading safetensors checkpoint shards:  93% Completed | 14/15 [00:15<00:01,  1.13s/it]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [00:16<00:00,  1.12s/it]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [00:16<00:00,  1.13s/it]
(EngineCore pid=38281)

(EngineCore pid=38281) INFO 05-18 19:17:44 [default_loader.py:384] Loading weights took 17.00 seconds
(EngineCore pid=38281) INFO 05-18 19:17:44 [mxfp4.py:1270] Using MoEPrepareAndFinalizeNoDPEPModular
(EngineCore pid=38281) INFO 05-18 19:17:48 [gpu_model_runner.py:4879] Model loading took 65.96 GiB memory and 21.746104 seconds
(EngineCore pid=38281) INFO 05-18 19:17:53 [backends.py:1069] Using cache directory: /home/sabrina/.cache/vllm/torch_compile_cache/f4c8f0b304/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=38281) INFO 05-18 19:17:53 [backends.py:1128] Dynamo bytecode transform time: 4.33 s
(EngineCore pid=38281) INFO 05-18 19:17:55 [backends.py:290] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 2.016 s
(EngineCore pid=38281) INFO 05-18 19:17:55 [decorators.py:305] Directly load AOT compilation from path /home/sabrina/.cache/vllm/torch_compile_cache/torch_aot_compile/7a43e81702567afb7628424be90c829626ff77baa4407541428249267a5ee258/rank_0_0/model
(EngineCore pid=38281) INFO 05-18 19:17:55 [monitor.py:53] torch.compile took 6.76 s in total
(EngineCore pid=38281) INFO 05-18 19:17:56 [monitor.py:81] Initial profiling/warmup run took 0.37 s
(EngineCore pid=38281) INFO 05-18 19:17:57 [gpu_model_runner.py:5963] Profiling CUDA graph memory: PIECEWISE=83 (largest=1024), FULL=35 (largest=256)
(EngineCore pid=38281) INFO 05-18 19:17:59 [gpu_model_runner.py:6042] Estimated CUDA graph memory: 0.96 GiB total
(EngineCore pid=38281) INFO 05-18 19:17:59 [gpu_worker.py:440] Available KV cache memory: 2.9 GiB
(EngineCore pid=38281) INFO 05-18 19:17:59 [gpu_worker.py:455] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.9000 is equivalent to --gpu-memory-utilization=0.8879 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.9121. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
(EngineCore pid=38281) INFO 05-18 19:17:59 [kv_cache_utils.py:1708] GPU KV cache size: 46,055 tokens
(EngineCore pid=38281) INFO 05-18 19:17:59 [kv_cache_utils.py:1709] Maximum concurrency for 10,000 tokens per request: 4.61x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 83/83 [00:09<00:00,  8.63it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:03<00:00,  9.34it/s]

(EngineCore pid=38281) INFO 05-18 19:18:14 [gpu_model_runner.py:6133] Graph capturing finished in 14 secs, took 0.95 GiB
(EngineCore pid=38281) INFO 05-18 19:18:14 [gpu_worker.py:599] CUDA graph pool memory: 0.95 GiB (actual), 0.96 GiB (estimated), difference: 0.01 GiB (1.2%).
(EngineCore pid=38281) INFO 05-18 19:18:14 [core.py:299] init engine (profile, create kv cache, warmup model) took 25.93 s (compilation: 6.76 s)
(EngineCore pid=38281) INFO 05-18 19:18:15 [kernel.py:205] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'])

Rendering prompts: 100%|██████████| 470/470 [00:03<00:00, 120.55it/s]
Processed prompts: 100%|██████████| 470/470 [18:18<00:00,  2.34s/it, est. speed input: 1042.50 toks/s, output: 788.50 toks/s]
Loading weights: 100%|██████████| 310/310 [00:00<00:00, 4667.33it/s]

(EngineCore pid=38281) INFO 05-18 19:41:10 [core.py:1238] Shutdown initiated (timeout=0)
(EngineCore pid=38281) INFO 05-18 19:41:10 [core.py:1261] Shutdown complete

### Remote mode

Run this cell instead of the local-mode cell if you want to send trial summarization requests to an existing OpenAI-compatible endpoint. If you do not already have a vLLM server running, `start_vllm_server(...)` can start one from the config values.

In [ ]:
from matchminer_ai import load_preset
from matchminer_ai.trials import summarize_trials
# from matchminer_ai.llm.vllm_server import start_vllm_server

os.environ["OPENAI_API_KEY"] = "not-needed"

# Optional: start a local vLLM server if you do not already have one.
# Optional: choose GPUs for the server process before starting it.
# os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"
# process = start_vllm_server(task="trial")

config = load_preset("default")
config.remote["enabled"] = True
config.remote["server_urls"] = ["http://localhost:8000/v1"]

trial_results, metadata, qc_report = summarize_trials(
    trials, config=config, return_metadata=True, return_qc=True
)

# Optional: stop the local vLLM server if you started it above.
# process.terminate()

### View results

In [4]:
trial_results.head()

,trial_id,clinical_space_number,clinical_space_summary,general_exclusion_criteria,space_trial_id
0,NCT03319901,1,Age range allowed: ≥60 years. Sex allowed: bot...,Pregnancy or breastfeeding; uncontrolled infec...,NCT03319901-1
1,NCT03319901,2,Age range allowed: ≥18 years. Sex allowed: bot...,Pregnancy or breastfeeding; uncontrolled infec...,NCT03319901-2
2,NCT04792489,1,Age range allowed: ≥18 years. Sex allowed: Mal...,History of human immunodeficiency virus infect...,NCT04792489-1
3,NCT04792489,2,Age range allowed: ≥18 years. Sex allowed: Mal...,History of human immunodeficiency virus infect...,NCT04792489-2
4,NCT04792489,3,Age range allowed: ≥18 years. Sex allowed: Mal...,History of human immunodeficiency virus infect...,NCT04792489-3

Metadata contains a snapshot of the config used and metadata on the model used.

In [5]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'local': {'trial': {'max_model_len': 10000,
    'tensor_parallel_size': 1,
    'gpu_memory_utilization': 0.9},
   'patient': {'max_model_len': 70000,
    'tensor_parallel_size': 1,
    'gpu_memory_utilization': 0.9}},
  'remote': {'enabled': False,
   'server_urls': ['http://localhost:8000/v1'],
   'max_concurrent_requests': 16,
   'request_timeout': 600,
   'max_retries': 6,
   'batch_size': 1000,
   'retry_backoff_base': 1.0},
  'trial': {'model_name': 'openai/gpt-oss-120b',
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n'},
  'patient': {'model_name': 'openai/gpt-oss-120b',
   'chunk_size': 10000,
   'chunk_overlap': 500,
   'prompt_margin_tokens': 5000,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'patient.serial.user.primer.txt',
    'question': 'patient.serial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\s*Boilerplate\\s*:?\\s*',
   'text_token_threshold': 115000},
  'embedding': {'model_path': 'ksg-dfci/TrialSpace-0426',
   'device': 'cpu',
   'prompt_file': 'embedding.txt'},
  'match_quality': {'model_name': 'ksg-dfci/TrialChecker-0426',
   'device': 'cuda',
   'prompt_file': 'match_quality_checker_template.txt',
   'score_cutoff': 0.2},
  'exclusion_criteria': {'model_name': 'ksg-dfci/BoilerPlateChecker-0426',
   'device': 'cuda',
   'prompt_file': 'exclusion_criteria_checker_template.txt'}},
 'model_metadata': {'trial_summarizer': {'model_name': 'openai/gpt-oss-120b',
   'model_sha': 'b5c939de8f754692c1647ca79fbf85e8c1e70f8a',
   'created_at': '2025-08-04T22:33:06+00:00',
   'last_modified': '2025-08-26T17:25:03+00:00'}}}

QC report on the trial summarization run

In [6]:
qc_report

,metric,value,denominator,percent,ids
0,trials_missing_in_output,1.0,470.0,0.212766,[NCT05922501]
1,trials_truncated_llm_response,0.0,470.0,0.000000,[]
2,spaces_exceed_embedding_token_limit,0.0,1449.0,0.000000,[]
3,spaces_per_trial_min,1.0,NaN,NaN,[]
4,spaces_per_trial_median,2.0,NaN,NaN,[]
5,spaces_per_trial_max,33.0,NaN,NaN,[]
6,trials_with_non_distinct_spaces,3.0,469.0,0.639659,"[NCT05098132, NCT05484622, NCT05508906]"
7,spaces_dropped_missing_keyword:Age,0.0,1450.0,0.000000,[]
8,spaces_dropped_missing_keyword:Sex,0.0,1450.0,0.000000,[]
9,spaces_dropped_missing_keyword:Cancer type,0.0,1450.0,0.000000,[]
10,spaces_dropped_missing_keyword:Histology,0.0,1450.0,0.000000,[]
11,spaces_dropped_missing_keyword:Cancer burden,0.0,1450.0,0.000000,[]
12,spaces_dropped_missing_keyword:Prior treatment...,0.0,1450.0,0.000000,[]
13,spaces_dropped_missing_keyword:Prior treatment...,0.0,1450.0,0.000000,[]
14,spaces_dropped_missing_keyword:Biomarkers requ...,0.0,1450.0,0.000000,[]
15,spaces_dropped_missing_keyword:Biomarkers excl...,1.0,1450.0,0.068966,[NCT05922501-1]
16,trials_exclusion_criteria_not_extracted,8.0,469.0,1.705757,"[NCT04775485, NCT05417594, NCT05519085, NCT056..."

Save checked-in trial example artifacts

In [ ]:
trial_results.to_csv("output/trial_summaries.csv", index=None)
with open("output/trial_summarization_metadata.json", "w") as f:
    json.dump(metadata, f, indent=2)
qc_report.to_csv("output/trial_qc_report.csv", index=None)

## 2. Patient summarization walkthrough

### Read in data

In [8]:
notes_path = "data/2026_01_16_dummy_notes.csv"
notes = pd.read_csv(notes_path)
notes.head()

,patient_id,note_date,note_text,NOTE_SOURCE,LAST_MOD,PROVIDER_TYPE,RPT_STATUS,ENCOUNTER_TYPE_DESC,PROVIDER_DEPT,PROC_DESC
0,-1,6/20/25,**Imaging Report**\n\n---\n\n**Patient:** Mich...,Imaging,6/25/25,PROVIDER_TYPE_NM,NOTE_STATUS_DESCR,ENCOUNTER_TYPE_DESCR,NaN,NaN
1,-1,6/25/25,**Oncology Progress Note – Follow‑Up Visit**\n...,progress_notesbase,6/25/25,Physician,Signed,Office Visit,NaN,NaN
2,-2,6/19/25,**Imaging Report**\n\n**Patient:** Daniel O’Co...,Imaging,6/25/25,PROVIDER_TYPE_NM,NOTE_STATUS_DESCR,ENCOUNTER_TYPE_DESCR,NaN,NaN
3,-2,6/20/25,**Oncology Progress Note**\n\n**Patient:** Dan...,progress_notesbase,6/25/25,Physician,Signed,Office Visit,NaN,NaN
4,-2,6/25/25,**Oncology Progress Note – Follow‑up Visit**\n...,progress_notesbase,6/25/25,Physician,Signed,Office Visit,NaN,NaN

### Local mode

`summarize_patients(...)` uses the local in-memory vLLM backend by default. Run this cell if you want local mode.

In [9]:
from matchminer_ai.patients import summarize_patients

patient_summaries, metadata, qc_report = summarize_patients(
    notes, return_metadata=True, return_qc=True
)

# Optional: clear the cached local vLLM engine if GPU memory is tight.
# from matchminer_ai.llm.backends import clear_local_llm_cache
# clear_local_llm_cache()

/home/sabrina/mmai-package/src/matchminer_ai/patients/prepare.py:31: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  normalized["note_date"] = pd.to_datetime(normalized["note_date"])

INFO 05-18 19:41:20 [utils.py:233] non-default args: {'max_model_len': 70000, 'gpu_memory_utilization': 0.9, 'disable_log_stats': True, 'model': 'openai/gpt-oss-120b'}
INFO 05-18 19:41:20 [model.py:555] Resolved architecture: GptOssForCausalLM

Parse safetensors files: 100%|██████████| 15/15 [00:00<00:00, 99.11it/s]

INFO 05-18 19:41:21 [model.py:1680] Using max model len 70000
INFO 05-18 19:41:21 [config.py:170] Overriding max cuda graph capture size to 1024 for performance.
INFO 05-18 19:41:21 [kernel.py:205] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'])

(EngineCore pid=43983) INFO 05-18 19:41:21 [core.py:109] Initializing a V1 LLM engine (v0.20.2) with config: model='openai/gpt-oss-120b', speculative_config=None, tokenizer='openai/gpt-oss-120b', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=70000, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=gpt_oss_mxfp4, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='openai_gptoss', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=openai/gpt-oss-120b, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto')
(EngineCore pid=43983) INFO 05-18 19:41:21 [parallel_state.py:1402] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.128.0.42:47903 backend=nccl
(EngineCore pid=43983) INFO 05-18 19:41:21 [parallel_state.py:1715] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank 0, EPLB rank N/A
(EngineCore pid=43983) INFO 05-18 19:41:22 [gpu_model_runner.py:4777] Starting to load model openai/gpt-oss-120b...
(EngineCore pid=43983) INFO 05-18 19:41:24 [cuda.py:368] Using TRITON_ATTN attention backend out of potential backends: ['TRITON_ATTN'].
(EngineCore pid=43983) INFO 05-18 19:41:24 [mxfp4.py:401] Using 'MARLIN' Mxfp4 MoE backend.
(EngineCore pid=43983) INFO 05-18 19:41:24 [weight_utils.py:904] Filesystem type for checkpoints: EXT4. Checkpoint size: 60.77 GiB. Available RAM: 154.88 GiB.
(EngineCore pid=43983) INFO 05-18 19:41:24 [weight_utils.py:927] Auto-prefetch is disabled because the filesystem (EXT4) is not a recognized network FS (NFS/Lustre). If you want to force prefetching, start vLLM with --safetensors-load-strategy=prefetch.

Loading safetensors checkpoint shards:   0% Completed | 0/15 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   7% Completed | 1/15 [00:01<00:16,  1.20s/it]
Loading safetensors checkpoint shards:  13% Completed | 2/15 [00:02<00:14,  1.12s/it]
Loading safetensors checkpoint shards:  20% Completed | 3/15 [00:03<00:13,  1.15s/it]
Loading safetensors checkpoint shards:  27% Completed | 4/15 [00:04<00:12,  1.12s/it]
Loading safetensors checkpoint shards:  33% Completed | 5/15 [00:05<00:11,  1.15s/it]
Loading safetensors checkpoint shards:  40% Completed | 6/15 [00:06<00:10,  1.13s/it]
Loading safetensors checkpoint shards:  47% Completed | 7/15 [00:08<00:09,  1.15s/it]
Loading safetensors checkpoint shards:  53% Completed | 8/15 [00:09<00:07,  1.12s/it]
Loading safetensors checkpoint shards:  60% Completed | 9/15 [00:10<00:06,  1.15s/it]
Loading safetensors checkpoint shards:  67% Completed | 10/15 [00:11<00:05,  1.13s/it]
Loading safetensors checkpoint shards:  73% Completed | 11/15 [00:12<00:04,  1.15s/it]
Loading safetensors checkpoint shards:  80% Completed | 12/15 [00:13<00:03,  1.13s/it]
Loading safetensors checkpoint shards:  87% Completed | 13/15 [00:14<00:02,  1.10s/it]
Loading safetensors checkpoint shards:  93% Completed | 14/15 [00:15<00:01,  1.13s/it]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [00:16<00:00,  1.11s/it]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [00:16<00:00,  1.13s/it]
(EngineCore pid=43983)

(EngineCore pid=43983) INFO 05-18 19:41:41 [default_loader.py:384] Loading weights took 16.97 seconds
(EngineCore pid=43983) INFO 05-18 19:41:41 [mxfp4.py:1270] Using MoEPrepareAndFinalizeNoDPEPModular
(EngineCore pid=43983) INFO 05-18 19:41:46 [gpu_model_runner.py:4879] Model loading took 65.96 GiB memory and 21.676782 seconds
(EngineCore pid=43983) INFO 05-18 19:41:50 [backends.py:1069] Using cache directory: /home/sabrina/.cache/vllm/torch_compile_cache/73cdf7d7e3/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=43983) INFO 05-18 19:41:50 [backends.py:1128] Dynamo bytecode transform time: 4.43 s
(EngineCore pid=43983) INFO 05-18 19:41:52 [backends.py:290] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 1.468 s
(EngineCore pid=43983) INFO 05-18 19:41:52 [decorators.py:305] Directly load AOT compilation from path /home/sabrina/.cache/vllm/torch_compile_cache/torch_aot_compile/54d6522c25a4cec98030cecb1f847b789b67db2e57f32a17b6ba4119cdb11f4f/rank_0_0/model
(EngineCore pid=43983) INFO 05-18 19:41:52 [monitor.py:53] torch.compile took 6.32 s in total
(EngineCore pid=43983) INFO 05-18 19:41:53 [monitor.py:81] Initial profiling/warmup run took 0.24 s
(EngineCore pid=43983) INFO 05-18 19:41:54 [gpu_model_runner.py:5963] Profiling CUDA graph memory: PIECEWISE=83 (largest=1024), FULL=35 (largest=256)
(EngineCore pid=43983) INFO 05-18 19:41:56 [gpu_model_runner.py:6042] Estimated CUDA graph memory: 0.96 GiB total
(EngineCore pid=43983) INFO 05-18 19:41:56 [gpu_worker.py:440] Available KV cache memory: 2.9 GiB
(EngineCore pid=43983) INFO 05-18 19:41:56 [gpu_worker.py:455] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.9000 is equivalent to --gpu-memory-utilization=0.8879 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.9121. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
(EngineCore pid=43983) INFO 05-18 19:41:56 [kv_cache_utils.py:1708] GPU KV cache size: 75,490 tokens
(EngineCore pid=43983) INFO 05-18 19:41:56 [kv_cache_utils.py:1709] Maximum concurrency for 70,000 tokens per request: 1.08x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 83/83 [00:09<00:00,  8.58it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:07<00:00,  4.56it/s]

(EngineCore pid=43983) INFO 05-18 19:42:15 [gpu_model_runner.py:6133] Graph capturing finished in 18 secs, took 0.95 GiB
(EngineCore pid=43983) INFO 05-18 19:42:15 [gpu_worker.py:599] CUDA graph pool memory: 0.95 GiB (actual), 0.96 GiB (estimated), difference: 0.01 GiB (1.2%).
(EngineCore pid=43983) INFO 05-18 19:42:15 [core.py:299] init engine (profile, create kv cache, warmup model) took 29.47 s (compilation: 6.32 s)
(EngineCore pid=43983) INFO 05-18 19:42:16 [kernel.py:205] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'])

Rendering prompts: 100%|██████████| 12/12 [00:00<00:00, 42.53it/s]
Processed prompts: 100%|██████████| 12/12 [00:37<00:00,  3.12s/it, est. speed input: 1719.68 toks/s, output: 453.27 toks/s]
Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 48.07it/s]
Processed prompts: 100%|██████████| 1/1 [00:02<00:00,  2.50s/it, est. speed input: 2017.19 toks/s, output: 117.88 toks/s]

### Remote mode

Run this cell instead of the local-mode cell if you want to send patient summarization requests to an existing OpenAI-compatible endpoint. If you do not already have a vLLM server running, `start_vllm_server(...)` can start one from the config values.

In [ ]:
from matchminer_ai import load_preset
from matchminer_ai.patients import summarize_patients
# from matchminer_ai.llm.vllm_server import start_vllm_server

os.environ["OPENAI_API_KEY"] = "not-needed"

# Optional: start a local vLLM server if you do not already have one.
# Optional: choose GPUs for the server process before starting it.
# os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"
# process = start_vllm_server(task="patient")

config = load_preset("default")
config.remote["enabled"] = True
config.remote["server_urls"] = ["http://localhost:8000/v1"]

patient_summaries, metadata, qc_report = summarize_patients(
    notes, config=config, return_metadata=True, return_qc=True
)

# Optional: stop the local vLLM server if you started it above.
# process.terminate()

### View results

In [10]:
patient_summaries

,patient_id,last_note_date,cancer_history_summary,general_exclusion_criteria_evidence
0,-1,2025-06-25,Age: 64\nSex: Male\nCancer type: Gastroesophag...,No evidence of commonly used trial exclusion c...
1,-10,2025-06-25,Age: 55\nSex: Female\nCancer type: Ovarian can...,No evidence of common boilerplate exclusion cr...
2,-11,2025-06-25,Age: 68 \nSex: Male \nCancer type: Cutaneous...,- No untreated/uncontrolled brain metastasis (...
3,-12,2025-06-25,Age: 19\nSex: Male\nCancer type: Osteosarcoma\...,No evidence of common exclusion criteria – ECO...
4,-2,2025-06-25,Age: 34\nSex: Male\nCancer type: Appendiceal n...,No evidence of commonly excluded trial criteri...
5,-3,2025-06-25,Age: 66\nSex: Male\nCancer type: Right breast ...,No evidence of common boilerplate exclusion cr...
6,-4,2025-06-25,Age: 62 \nSex: Female \nCancer type: Gliobla...,• Hypertension presently suboptimally controll...
7,-5,2025-06-25,Age: 45\nSex: Female\nCancer type: Breast canc...,No evidence of commonly cited trial exclusion ...
8,-6,2025-06-25,Age: 68\nSex: Male\nCancer type: Small‑cell lu...,No evidence of common exclusion criteria (no u...
9,-7,2025-06-25,Age: 70\nSex: Male\nCancer type: Prostate canc...,Controlled hypertension on amlodipine; cardiov...
10,-8,2025-06-25,Age: 76\nSex: Female\nCancer type: High‑grade ...,No evidence of commonly excluded comorbidities...
11,-9,2025-06-25,,

Metadata contains a snapshot of the config used and metadata on the models used.

In [11]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'local': {'trial': {'max_model_len': 10000,
    'tensor_parallel_size': 1,
    'gpu_memory_utilization': 0.9},
   'patient': {'max_model_len': 70000,
    'tensor_parallel_size': 1,
    'gpu_memory_utilization': 0.9}},
  'remote': {'enabled': False,
   'server_urls': ['http://localhost:8000/v1'],
   'max_concurrent_requests': 16,
   'request_timeout': 600,
   'max_retries': 6,
   'batch_size': 1000,
   'retry_backoff_base': 1.0},
  'trial': {'model_name': 'openai/gpt-oss-120b',
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n'},
  'patient': {'model_name': 'openai/gpt-oss-120b',
   'chunk_size': 10000,
   'chunk_overlap': 500,
   'prompt_margin_tokens': 5000,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'patient.serial.user.primer.txt',
    'question': 'patient.serial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\s*Boilerplate\\s*:?\\s*',
   'text_token_threshold': 115000},
  'embedding': {'model_path': 'ksg-dfci/TrialSpace-0426',
   'device': 'cpu',
   'prompt_file': 'embedding.txt'},
  'match_quality': {'model_name': 'ksg-dfci/TrialChecker-0426',
   'device': 'cuda',
   'prompt_file': 'match_quality_checker_template.txt',
   'score_cutoff': 0.2},
  'exclusion_criteria': {'model_name': 'ksg-dfci/BoilerPlateChecker-0426',
   'device': 'cuda',
   'prompt_file': 'exclusion_criteria_checker_template.txt'}},
 'model_metadata': {'patient_summarizer': {'model_name': 'openai/gpt-oss-120b',
   'model_sha': 'b5c939de8f754692c1647ca79fbf85e8c1e70f8a',
   'created_at': '2025-08-04T22:33:06+00:00',
   'last_modified': '2025-08-26T17:25:03+00:00'}}}

QC report on patient summarization

In [12]:
qc_report

,metric,value,denominator,percent,ids
0,patients_dropped_noninformative_summary,0,12,0.000000,[]
1,patients_exceed_embedding_token_limit,0,12,0.000000,[]
2,patients_exclusion_criteria_not_extracted,1,12,8.333333,[-9]
3,patients_missing_keyword:Age,1,12,8.333333,[-9]
4,patients_missing_keyword:Sex,1,12,8.333333,[-9]
5,patients_missing_keyword:Cancer type,1,12,8.333333,[-9]
6,patients_missing_keyword:Histology,1,12,8.333333,[-9]
7,patients_missing_keyword:Current extent,1,12,8.333333,[-9]
8,patients_missing_keyword:Biomarkers,1,12,8.333333,[-9]
9,patients_missing_keyword:Treatment history,1,12,8.333333,[-9]

Save checked-in patient example artifacts

In [13]:
patient_summaries.to_csv("output/patient_summaries.csv", index=None)
with open("output/patient_summarization_metadata.json", "w") as f:
    json.dump(metadata, f, indent=2)
qc_report.to_csv("output/patient_qc_report.csv", index=None)

## 3. Embed summarized entities for matching

In [14]:
from matchminer_ai.embedding import embed_for_matching

In [15]:
# Uncomment if you want to start from previously generated summaries
# trial_results = pd.read_csv("output/trial_summaries.csv")
# patient_summaries = pd.read_csv("output/patient_summaries.csv", dtype="str")

### Trials

In [16]:
embedded_trials, metadata = embed_for_matching(
    trial_results, entity_type="trial", return_metadata=True
)

In [17]:
embedded_trials.head()

  space_trial_id                                          embedding
0  NCT03319901-1  [0.03130612149834633, 0.019835270941257477, -0...
1  NCT03319901-2  [0.002635795855894685, 0.0012588619720190763, ...
2  NCT04792489-1  [-0.033495958894491196, -0.03904451057314873, ...
3  NCT04792489-2  [0.04088600352406502, 0.01079018134623766, 0.0...
4  NCT04792489-3  [-0.025599565356969833, 0.010473771020770073, ...

Metadata contains a snapshot of the config used and metadata on the models used.

In [18]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'local': {'trial': {'max_model_len': 10000,
    'tensor_parallel_size': 1,
    'gpu_memory_utilization': 0.9},
   'patient': {'max_model_len': 70000,
    'tensor_parallel_size': 1,
    'gpu_memory_utilization': 0.9}},
  'remote': {'enabled': False,
   'server_urls': ['http://localhost:8000/v1'],
   'max_concurrent_requests': 16,
   'request_timeout': 600,
   'max_retries': 6,
   'batch_size': 1000,
   'retry_backoff_base': 1.0},
  'trial': {'model_name': 'openai/gpt-oss-120b',
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n'},
  'patient': {'model_name': 'openai/gpt-oss-120b',
   'chunk_size': 10000,
   'chunk_overlap': 500,
   'prompt_margin_tokens': 5000,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'patient.serial.user.primer.txt',
    'question': 'patient.serial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\s*Boilerplate\\s*:?\\s*',
   'text_token_threshold': 115000},
  'embedding': {'model_path': 'ksg-dfci/TrialSpace-0426',
   'device': 'cpu',
   'prompt_file': 'embedding.txt'},
  'match_quality': {'model_name': 'ksg-dfci/TrialChecker-0426',
   'device': 'cuda',
   'prompt_file': 'match_quality_checker_template.txt',
   'score_cutoff': 0.2},
  'exclusion_criteria': {'model_name': 'ksg-dfci/BoilerPlateChecker-0426',
   'device': 'cuda',
   'prompt_file': 'exclusion_criteria_checker_template.txt'}},
 'model_metadata': {'embedding_model': {'model_name': 'ksg-dfci/TrialSpace-0426',
   'model_sha': '074a536a28192a2bd814bc95863f71dc42028c34',
   'created_at': '2026-04-06T13:59:34+00:00',
   'last_modified': '2026-04-06T14:10:11+00:00'}}}

### Patients

In [19]:
embedded_patients, metadata = embed_for_matching(
    patient_summaries, entity_type="patient", return_metadata=True
)

In [20]:
embedded_patients.head()

  patient_id                                          embedding
0         -1  [0.04996487870812416, -0.01829705201089382, -0...
1        -10  [-0.055610399693250656, -0.03643682226538658, ...
2        -11  [0.017326446250081062, -0.011801098473370075, ...
3        -12  [0.0010062502697110176, -0.0004548628930933773...
4         -2  [-0.00955837219953537, -0.02855365164577961, -...

Metadata contains a snapshot of the config used and metadata on the models used.

In [21]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'local': {'trial': {'max_model_len': 10000,
    'tensor_parallel_size': 1,
    'gpu_memory_utilization': 0.9},
   'patient': {'max_model_len': 70000,
    'tensor_parallel_size': 1,
    'gpu_memory_utilization': 0.9}},
  'remote': {'enabled': False,
   'server_urls': ['http://localhost:8000/v1'],
   'max_concurrent_requests': 16,
   'request_timeout': 600,
   'max_retries': 6,
   'batch_size': 1000,
   'retry_backoff_base': 1.0},
  'trial': {'model_name': 'openai/gpt-oss-120b',
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n'},
  'patient': {'model_name': 'openai/gpt-oss-120b',
   'chunk_size': 10000,
   'chunk_overlap': 500,
   'prompt_margin_tokens': 5000,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'patient.serial.user.primer.txt',
    'question': 'patient.serial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\s*Boilerplate\\s*:?\\s*',
   'text_token_threshold': 115000},
  'embedding': {'model_path': 'ksg-dfci/TrialSpace-0426',
   'device': 'cpu',
   'prompt_file': 'embedding.txt'},
  'match_quality': {'model_name': 'ksg-dfci/TrialChecker-0426',
   'device': 'cuda',
   'prompt_file': 'match_quality_checker_template.txt',
   'score_cutoff': 0.2},
  'exclusion_criteria': {'model_name': 'ksg-dfci/BoilerPlateChecker-0426',
   'device': 'cuda',
   'prompt_file': 'exclusion_criteria_checker_template.txt'}},
 'model_metadata': {'embedding_model': {'model_name': 'ksg-dfci/TrialSpace-0426',
   'model_sha': '074a536a28192a2bd814bc95863f71dc42028c34',
   'created_at': '2026-04-06T13:59:34+00:00',
   'last_modified': '2026-04-06T14:10:11+00:00'}}}

In [22]:
# Optional local export if you want to reuse embeddings without rerunning this step.
embedded_patients.to_parquet("output/embedded_patients.parquet")
embedded_trials.to_parquet("output/embedded_trials.parquet")

## 4. Generate candidate matches

Generate ranked trial-space candidates for each patient.

In [23]:
from matchminer_ai.matching import generate_candidate_matches

In [24]:
# Uncomment if you saved embeddings locally and want to start from them
# embedded_patients = pd.read_parquet('output/embedded_patients.parquet')
# embedded_trials = pd.read_parquet('output/embedded_trials.parquet')

### Candidate matches

In [25]:
candidate_matches = generate_candidate_matches(
    query_df=embedded_patients, corpus_df=embedded_trials
)

In [26]:
candidate_matches.head()

  patient_id space_trial_id  similarity_score  rank
0         -1  NCT05482893-1          0.597789     1
1         -1  NCT06293898-8          0.587092     2
2         -1  NCT05372614-2          0.580715     3
3         -1  NCT05482893-3          0.552987     4
4         -1  NCT06586957-4          0.545472     5

## 5. Match quality check

In [29]:
from matchminer_ai.matching import score_match_quality

Add back the patient and trial summary context required by the match-quality checker.

In [30]:
candidate_matches_with_context = (
    candidate_matches.merge(
        patient_summaries[["patient_id", "cancer_history_summary"]],
        on="patient_id",
        how="left",
    ).merge(
        trial_results[["space_trial_id", "clinical_space_summary"]],
        on="space_trial_id",
        how="left",
    )
)
candidate_matches_with_context.head()

,patient_id,space_trial_id,similarity_score,rank,cancer_history_summary,clinical_space_summary
0,-1,NCT05482893-1,0.597789,1,Age: 64\nSex: Male\nCancer type: Gastroesophag...,Age range allowed: 18 years or older. Sex allo...
1,-1,NCT06293898-8,0.587092,2,Age: 64\nSex: Male\nCancer type: Gastroesophag...,Age range allowed: ≥18 years. Sex allowed: Bot...
2,-1,NCT05372614-2,0.580715,3,Age: 64\nSex: Male\nCancer type: Gastroesophag...,Age range allowed: ≥ 18 years. Sex allowed: bo...
3,-1,NCT05482893-3,0.552987,4,Age: 64\nSex: Male\nCancer type: Gastroesophag...,Age range allowed: 18 years or older. Sex allo...
4,-1,NCT06586957-4,0.545472,5,Age: 64\nSex: Male\nCancer type: Gastroesophag...,Age range allowed: ≥18 years. Sex allowed: Mal...

Run the match-quality checker.

In [31]:
match_quality_matches, metadata = score_match_quality(
    candidate_matches_with_context, return_metadata=True
)

Loading weights: 100%|██████████| 174/174 [00:00<00:00, 4438.34it/s]

In [32]:
match_quality_matches.head()

  patient_id space_trial_id  match_quality_score  match_quality_pass
0         -1  NCT05482893-1             0.805589                True
1         -1  NCT06293898-8             0.989033                True
2         -1  NCT05372614-2             0.980715                True
3         -1  NCT05482893-3             0.793689                True
4         -1  NCT06586957-4             0.718069                True

In [33]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'local': {'trial': {'max_model_len': 10000,
    'tensor_parallel_size': 1,
    'gpu_memory_utilization': 0.9},
   'patient': {'max_model_len': 70000,
    'tensor_parallel_size': 1,
    'gpu_memory_utilization': 0.9}},
  'remote': {'enabled': False,
   'server_urls': ['http://localhost:8000/v1'],
   'max_concurrent_requests': 16,
   'request_timeout': 600,
   'max_retries': 6,
   'batch_size': 1000,
   'retry_backoff_base': 1.0},
  'trial': {'model_name': 'openai/gpt-oss-120b',
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n'},
  'patient': {'model_name': 'openai/gpt-oss-120b',
   'chunk_size': 10000,
   'chunk_overlap': 500,
   'prompt_margin_tokens': 5000,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'patient.serial.user.primer.txt',
    'question': 'patient.serial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\s*Boilerplate\\s*:?\\s*',
   'text_token_threshold': 115000},
  'embedding': {'model_path': 'ksg-dfci/TrialSpace-0426',
   'device': 'cpu',
   'prompt_file': 'embedding.txt'},
  'match_quality': {'model_name': 'ksg-dfci/TrialChecker-0426',
   'device': 'cuda',
   'prompt_file': 'match_quality_checker_template.txt',
   'score_cutoff': 0.2},
  'exclusion_criteria': {'model_name': 'ksg-dfci/BoilerPlateChecker-0426',
   'device': 'cuda',
   'prompt_file': 'exclusion_criteria_checker_template.txt'}},
 'model_metadata': {'match_quality_checker': {'model_name': 'ksg-dfci/TrialChecker-0426',
   'model_sha': '9317b80b5342f34477ad9c97ed9c73af7da100d9',
   'created_at': '2026-04-06T14:11:22+00:00',
   'last_modified': '2026-04-06T14:18:46+00:00'}}}

## 6. Exclusion criteria check

In [34]:
# limit to unique patient-trial ID pairs
match_quality_matches["trial_id"] = (
    match_quality_matches["space_trial_id"].str.split("-").str[0]
)
unique_patient_trial_pairs = match_quality_matches[
    ["patient_id", "trial_id"]
].drop_duplicates()

# add in exclusion criteria for patients and trials
patient_trial_pairs_with_exclusion_context = unique_patient_trial_pairs.merge(
    patient_summaries[["patient_id", "general_exclusion_criteria_evidence"]],
    on="patient_id",
    how="left",
).merge(
    trial_results[["trial_id", "general_exclusion_criteria"]].drop_duplicates(),
    on="trial_id",
    how="left",
)
patient_trial_pairs_with_exclusion_context.head()

,patient_id,trial_id,general_exclusion_criteria_evidence,general_exclusion_criteria
0,-1,NCT05482893,No evidence of commonly used trial exclusion c...,Women who are pregnant or breastfeeding.\nWome...
1,-1,NCT06293898,No evidence of commonly used trial exclusion c...,History of severe heart disease; prolonged cor...
2,-1,NCT05372614,No evidence of commonly used trial exclusion c...,History of interstitial lung disease or pneumo...
3,-1,NCT06586957,No evidence of commonly used trial exclusion c...,* Presence of a locoregional tumor amenable to...
4,-1,NCT06244485,No evidence of commonly used trial exclusion c...,Has previously been treated with any enhancer ...

In [35]:
from matchminer_ai.matching import exclusion_criteria_check

# run exclusion criteria check
exclusion_results, metadata = exclusion_criteria_check(
    patient_trial_pairs_with_exclusion_context, return_metadata=True
)
exclusion_results.head()

Loading weights: 100%|██████████| 174/174 [00:00<00:00, 4257.75it/s]

  patient_id     trial_id  exclusion_score  exclusion_criteria_pass
0         -1  NCT05482893         0.999986                     True
1         -1  NCT06293898         0.999994                     True
2         -1  NCT05372614         0.999993                     True
3         -1  NCT06586957         0.999989                     True
4         -1  NCT06244485         0.999997                     True

In [36]:
exclusion_results["exclusion_criteria_pass"].value_counts()

exclusion_criteria_pass
True     169
False      3
Name: count, dtype: int64

In [37]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'local': {'trial': {'max_model_len': 10000,
    'tensor_parallel_size': 1,
    'gpu_memory_utilization': 0.9},
   'patient': {'max_model_len': 70000,
    'tensor_parallel_size': 1,
    'gpu_memory_utilization': 0.9}},
  'remote': {'enabled': False,
   'server_urls': ['http://localhost:8000/v1'],
   'max_concurrent_requests': 16,
   'request_timeout': 600,
   'max_retries': 6,
   'batch_size': 1000,
   'retry_backoff_base': 1.0},
  'trial': {'model_name': 'openai/gpt-oss-120b',
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n'},
  'patient': {'model_name': 'openai/gpt-oss-120b',
   'chunk_size': 10000,
   'chunk_overlap': 500,
   'prompt_margin_tokens': 5000,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'patient.serial.user.primer.txt',
    'question': 'patient.serial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\s*Boilerplate\\s*:?\\s*',
   'text_token_threshold': 115000},
  'embedding': {'model_path': 'ksg-dfci/TrialSpace-0426',
   'device': 'cpu',
   'prompt_file': 'embedding.txt'},
  'match_quality': {'model_name': 'ksg-dfci/TrialChecker-0426',
   'device': 'cuda',
   'prompt_file': 'match_quality_checker_template.txt',
   'score_cutoff': 0.2},
  'exclusion_criteria': {'model_name': 'ksg-dfci/BoilerPlateChecker-0426',
   'device': 'cuda',
   'prompt_file': 'exclusion_criteria_checker_template.txt'}},
 'model_metadata': {'exclusion_criteria_checker': {'model_name': 'ksg-dfci/BoilerPlateChecker-0426',
   'model_sha': '74158a77c72fa4123c0deed52ba506924517e8d6',
   'created_at': '2026-04-06T14:19:20+00:00',
   'last_modified': '2026-04-06T14:37:02+00:00'}}}

## 7. Save final matches

Create one review table with one row per patient/trial pair. Each pair is represented by its top-scoring clinical space, rows are ranked by that top match-quality score, and exclusion-check results are included as labels without filtering rows.

In [ ]:
patient_context_cols = [
    col
    for col in [
        "patient_id",
        "cancer_history_summary",
        "general_exclusion_criteria_evidence",
    ]
    if col in patient_summaries.columns
]
trial_context_cols = [
    col
    for col in [
        "space_trial_id",
        "clinical_space_number",
        "clinical_space_summary",
        "general_exclusion_criteria",
    ]
    if col in trial_results.columns
]
original_trial_cols = [
    col
    for col in [
        "trial_id",
        "oncore_id",
        "trial_title",
        "brief_summary",
        "detailed_summary",
        "eligibility_criteria",
    ]
    if col in trials.columns
]

final_matches = (
    match_quality_matches.merge(
        candidate_matches[["patient_id", "space_trial_id", "similarity_score", "rank"]],
        on=["patient_id", "space_trial_id"],
        how="left",
    )
    .merge(
        exclusion_results,
        on=["patient_id", "trial_id"],
        how="left",
    )
    .merge(
        patient_summaries[patient_context_cols],
        on="patient_id",
        how="left",
    )
    .merge(
        trial_results[trial_context_cols].drop_duplicates("space_trial_id"),
        on="space_trial_id",
        how="left",
    )
    .merge(
        trials[original_trial_cols].drop_duplicates("trial_id"),
        on="trial_id",
        how="left",
    )
)

# Keep one row per patient/trial pair, represented by the top-scoring clinical space.
final_matches = (
    final_matches.sort_values(
        ["patient_id", "trial_id", "match_quality_score"],
        ascending=[True, True, False],
    )
    .drop_duplicates(["patient_id", "trial_id"], keep="first")
    .sort_values(["patient_id", "match_quality_score"], ascending=[True, False])
    .reset_index(drop=True)
)
final_matches["match_quality_rank"] = final_matches.groupby("patient_id").cumcount() + 1

final_matches = final_matches.rename(
    columns={
        "match_quality_rank": "match_rank",
        "exclusion_criteria_pass": "passes_exclusion_criteria",
        "cancer_history_summary": "patient_summary",
        "general_exclusion_criteria_evidence": "patient_exclusion_evidence",
        "brief_summary": "trial_brief_summary",
        "detailed_summary": "trial_detailed_summary",
        "eligibility_criteria": "trial_eligibility_criteria",
        "clinical_space_summary": "matched_clinical_space_summary",
        "general_exclusion_criteria": "extracted_trial_exclusion_criteria",
    }
)

ordered_cols = [
    "patient_id",
    "trial_id",
    "match_rank",
    "passes_exclusion_criteria",
    "patient_summary",
    "patient_exclusion_evidence",
    "oncore_id",
    "trial_title",
    "trial_brief_summary",
    "trial_detailed_summary",
    "trial_eligibility_criteria",
    "clinical_space_number",
    "matched_clinical_space_summary",
    "extracted_trial_exclusion_criteria",
]
final_matches = final_matches[[col for col in ordered_cols if col in final_matches.columns]]
final_matches.head()

In [ ]:
# Optional local export for review or downstream analysis.
final_matches.to_csv("output/final_matches.csv", index=None)