In [1]:
# general imports
import pandas as pd

# MMAI Examples

## Trial Summarization

### Read in data

In [2]:
trials_path = "data/scheduled__2025-09-04T230000+0000.trials_for_summarize.csv"
trials = pd.read_csv(trials_path)

### Convert column names to those expected by the function.
- `trial_id`
- `trial_title`
- `brief_summary`
- `eligibility_criteria`

In [3]:
trials.rename(columns = {'title':'trial_title', 'nct_id':'trial_id'},inplace= True)

### Run `summarize_trials` function.

*Note: You can turn debug mode on to add intermediate summarization outputs to the dataframe. Example below*
```python
from mmai import load_preset
config = load_preset("default")
config.debug_mode = True
df, metadata = summarize_trials(trials, config=config, return_metadata=True)
```

In [4]:
# import and run function on trial data
from mmai.trials import summarize_trials
trial_results, metadata = summarize_trials(trials, return_metadata=True)

/home/sabrina/mmai-package/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

INFO 02-02 19:13:23 [utils.py:261] non-default args: {'max_model_len': 10000, 'disable_log_stats': True, 'model': 'openai/gpt-oss-120b'}
INFO 02-02 19:13:23 [model.py:541] Resolved architecture: GptOssForCausalLM

Parse safetensors files: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s]

INFO 02-02 19:13:25 [model.py:1561] Using max model len 10000

2026-02-02 19:13:27,684	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.

INFO 02-02 19:13:27 [scheduler.py:226] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 02-02 19:13:27 [config.py:314] Overriding max cuda graph capture size to 1024 for performance.
INFO 02-02 19:13:27 [vllm.py:624] Asynchronous scheduling is enabled.
(EngineCore_DP0 pid=22893) INFO 02-02 19:13:29 [core.py:96] Initializing a V1 LLM engine (v0.15.0) with config: model='openai/gpt-oss-120b', speculative_config=None, tokenizer='openai/gpt-oss-120b', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=10000, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=mxfp4, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='openai_gptoss', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=openai/gpt-oss-120b, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer'], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': True, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': True}, 'local_cache_dir': None}
(EngineCore_DP0 pid=22893) INFO 02-02 19:13:30 [parallel_state.py:1212] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.128.0.4:60501 backend=nccl
(EngineCore_DP0 pid=22893) INFO 02-02 19:13:30 [parallel_state.py:1423] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
(EngineCore_DP0 pid=22893) INFO 02-02 19:13:31 [gpu_model_runner.py:4021] Starting to load model openai/gpt-oss-120b...

(EngineCore_DP0 pid=22893) /home/sabrina/mmai-package/.venv/lib/python3.13/site-packages/tvm_ffi/_optional_torch_c_dlpack.py:174: UserWarning: Failed to JIT torch c dlpack extension, EnvTensorAllocator will not be enabled.
(EngineCore_DP0 pid=22893) We recommend installing via `pip install torch-c-dlpack-ext`
(EngineCore_DP0 pid=22893)   warnings.warn(

(EngineCore_DP0 pid=22893) INFO 02-02 19:13:32 [cuda.py:364] Using TRITON_ATTN attention backend out of potential backends: ('TRITON_ATTN',)
(EngineCore_DP0 pid=22893) INFO 02-02 19:13:32 [mxfp4.py:161] Using Marlin backend

Loading safetensors checkpoint shards:   0% Completed | 0/15 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   7% Completed | 1/15 [00:01<00:18,  1.29s/it]
Loading safetensors checkpoint shards:  13% Completed | 2/15 [00:02<00:16,  1.25s/it]
Loading safetensors checkpoint shards:  20% Completed | 3/15 [00:03<00:15,  1.28s/it]
Loading safetensors checkpoint shards:  27% Completed | 4/15 [00:05<00:13,  1.25s/it]
Loading safetensors checkpoint shards:  33% Completed | 5/15 [00:06<00:12,  1.23s/it]
Loading safetensors checkpoint shards:  40% Completed | 6/15 [00:07<00:10,  1.21s/it]
Loading safetensors checkpoint shards:  47% Completed | 7/15 [00:08<00:10,  1.25s/it]
Loading safetensors checkpoint shards:  53% Completed | 8/15 [00:09<00:08,  1.23s/it]
Loading safetensors checkpoint shards:  60% Completed | 9/15 [00:11<00:07,  1.21s/it]
Loading safetensors checkpoint shards:  67% Completed | 10/15 [00:12<00:06,  1.20s/it]
Loading safetensors checkpoint shards:  73% Completed | 11/15 [00:13<00:04,  1.23s/it]
Loading safetensors checkpoint shards:  80% Completed | 12/15 [00:14<00:03,  1.26s/it]
Loading safetensors checkpoint shards:  87% Completed | 13/15 [00:16<00:02,  1.28s/it]
Loading safetensors checkpoint shards:  93% Completed | 14/15 [00:17<00:01,  1.29s/it]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [00:18<00:00,  1.26s/it]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [00:18<00:00,  1.25s/it]
(EngineCore_DP0 pid=22893)

(EngineCore_DP0 pid=22893) INFO 02-02 19:13:51 [default_loader.py:291] Loading weights took 18.80 seconds
(EngineCore_DP0 pid=22893) WARNING 02-02 19:13:51 [marlin_utils_fp4.py:336] Your GPU does not have native support for FP4 computation but FP4 quantization is being used. Weight-only FP4 compression will be used leveraging the Marlin kernel. This may degrade performance for compute-heavy workloads.
(EngineCore_DP0 pid=22893) INFO 02-02 19:13:55 [gpu_model_runner.py:4118] Model loading took 65.97 GiB memory and 23.166020 seconds
(EngineCore_DP0 pid=22893) INFO 02-02 19:14:05 [backends.py:805] Using cache directory: /home/sabrina/.cache/vllm/torch_compile_cache/bdd604333b/rank_0_0/backbone for vLLM's torch.compile
(EngineCore_DP0 pid=22893) INFO 02-02 19:14:05 [backends.py:865] Dynamo bytecode transform time: 8.82 s
(EngineCore_DP0 pid=22893) INFO 02-02 19:14:11 [backends.py:267] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 1.486 s
(EngineCore_DP0 pid=22893) INFO 02-02 19:14:11 [monitor.py:34] torch.compile takes 10.30 s in total
(EngineCore_DP0 pid=22893) INFO 02-02 19:14:12 [gpu_worker.py:356] Available KV cache memory: 3.34 GiB
(EngineCore_DP0 pid=22893) INFO 02-02 19:14:12 [kv_cache_utils.py:1307] GPU KV cache size: 48,688 tokens
(EngineCore_DP0 pid=22893) INFO 02-02 19:14:12 [kv_cache_utils.py:1312] Maximum concurrency for 10,000 tokens per request: 5.31x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 83/83 [00:08<00:00,  9.36it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:03<00:00,  9.26it/s]

(EngineCore_DP0 pid=22893) INFO 02-02 19:14:26 [gpu_model_runner.py:5051] Graph capturing finished in 14 secs, took 1.12 GiB
(EngineCore_DP0 pid=22893) INFO 02-02 19:14:26 [core.py:272] init engine (profile, create kv cache, warmup model) took 30.72 seconds
INFO 02-02 19:14:28 [llm.py:343] Supported tasks: ['generate']

Adding requests: 100%|██████████| 470/470 [00:03<00:00, 146.34it/s]
Processed prompts: 100%|██████████| 470/470 [16:18<00:00,  2.08s/it, est. speed input: 1169.39 toks/s, output: 871.82 toks/s]
[2026-02-02 19:30:51] INFO __init__.py:92: Completed LLM summarization. Beginning postprocessing.
[2026-02-02 19:30:53] INFO __init__.py:94: Postprocessing complete. Produced 1478 rows.

### View results

In [8]:
trial_results.head()

,trial_id,clinical_space_number,clinical_space_summary,general_exclusion_criteria,space_trial_id
0,NCT03319901,1,Age range allowed: Age ≥ 60 years. Sex allowed...,Patient is pregnant or nursing.\nUncontrolled ...,NCT03319901-1
1,NCT03319901,2,Age range allowed: Age ≥ 60 years. Sex allowed...,Patient is pregnant or nursing.\nUncontrolled ...,NCT03319901-2
2,NCT03319901,3,Age range allowed: Age ≥ 18 years. Sex allowed...,Patient is pregnant or nursing.\nUncontrolled ...,NCT03319901-3
4,NCT04792489,1,Age range allowed: >=18 years. Sex allowed: bo...,Unable to give informed consent.\nKnown histor...,NCT04792489-1
5,NCT04792489,2,Age range allowed: >=18 years. Sex allowed: bo...,Unable to give informed consent.\nKnown histor...,NCT04792489-2

Metadata contains a snapshot of the config used and metadata on the model used.

In [9]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'backend': 'local',
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'trial': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 10000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n'},
  'patient': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 120000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.2},
   'prompt_files': {'primer': 'patient.user.primer.txt',
    'question': 'patient.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n',
   'text_token_threshold': 115000,
   'tagger': {'model_name': 'ksg-dfci/TinyBertOncoTagger-1225',
    'device': 'cuda',
    'batch_size': 1024,
    'positive_tag_cutoff': 0.1,
    'negative_tag_cutoff': 0.9}}},
 'model_metadata': {'trial_summarizer': {'model_name': 'openai/gpt-oss-120b',
   'model_sha': 'b5c939de8f754692c1647ca79fbf85e8c1e70f8a',
   'created_at': '2025-08-04T22:33:06+00:00',
   'last_modified': '2025-08-26T17:25:03+00:00'}}}

Save example results

In [ ]:
import json
trial_results.to_csv('output/trial_summaries.csv', index = None)
with open("output/trial_summarization_metadata.json", "w") as f:
    json.dump(metadata, f, indent=2)

### Generate QC report

In [17]:
from mmai.qc.trials import trial_qc_report
qc_df = trial_qc_report(trial_results, trial_inputs=trials)
qc_df

,metric,value,percent,ids
0,trials_missing_summaries,2.0,0.425532,"[NCT06462183, NCT06619587]"
1,spaces_per_trial_min,1.0,NaN,[]
2,spaces_per_trial_median,2.0,NaN,[]
3,spaces_per_trial_max,33.0,NaN,[]
4,trials_with_non_distinct_spaces,1.0,0.212766,[NCT04777994]
5,spaces_missing_keyword:Age,0.0,0.000000,[]
6,spaces_missing_keyword:Sex,0.0,0.000000,[]
7,spaces_missing_keyword:Cancer type allowed,0.0,0.000000,[]
8,spaces_missing_keyword:Histology allowed,2.0,0.135318,"[NCT05315700-10, NCT05579366-13]"
9,spaces_missing_keyword:Cancer burden allowed,0.0,0.000000,[]
10,spaces_missing_keyword:Prior treatment required,0.0,0.000000,[]
11,spaces_missing_keyword:Prior treatment excluded,0.0,0.000000,[]
12,spaces_missing_keyword:Biomarkers required,0.0,0.000000,[]
13,spaces_missing_keyword:Biomarkers excluded,0.0,0.000000,[]
14,trials_missing_boilerplate_exclusions,14.0,2.978723,"[NCT00730444, NCT01656603, NCT04613596, NCT048..."
15,spaces_excessive_length,0.0,0.000000,[]

## Patient summarization

### Read in data

In [18]:
notes_path = "data/2026_01_16_dummy_notes.csv"
notes = pd.read_csv(notes_path)
notes.head()

,DFCI_MRN,EVENT_DATE,RPT_TEXT,NOTE_SOURCE,LAST_MOD,PROVIDER_TYPE,RPT_STATUS,ENCOUNTER_TYPE_DESC,PROVIDER_DEPT,PROC_DESC
0,-1,6/20/25,**Imaging Report**\n\n---\n\n**Patient:** Mich...,Imaging,6/25/25,PROVIDER_TYPE_NM,NOTE_STATUS_DESCR,ENCOUNTER_TYPE_DESCR,NaN,NaN
1,-1,6/25/25,**Oncology Progress Note – Follow‑Up Visit**\n...,progress_notesbase,6/25/25,Physician,Signed,Office Visit,NaN,NaN
2,-2,6/19/25,**Imaging Report**\n\n**Patient:** Daniel O’Co...,Imaging,6/25/25,PROVIDER_TYPE_NM,NOTE_STATUS_DESCR,ENCOUNTER_TYPE_DESCR,NaN,NaN
3,-2,6/20/25,**Oncology Progress Note**\n\n**Patient:** Dan...,progress_notesbase,6/25/25,Physician,Signed,Office Visit,NaN,NaN
4,-2,6/25/25,**Oncology Progress Note – Follow‑up Visit**\n...,progress_notesbase,6/25/25,Physician,Signed,Office Visit,NaN,NaN

### Convert column names to those expected by the function.
- `patient_id`
- `note_text`
- `note_type`
- `note_date`

In [19]:
notes.rename(columns = {'DFCI_MRN': 'patient_id', 'RPT_TEXT':'note_text', 'NOTE_SOURCE':'note_type', 'EVENT_DATE':'note_date'}, inplace = True)

### Run patient summarization

*Note: You can turn debug mode on to add intermediate summarization outputs to the dataframe. Example below*
```python
from mmai import load_preset
config = load_preset("default")
config.debug_mode = True
df, metadata = summarize_patients(notes, config=config, return_metadata=True)
```

In [27]:
from mmai.patients import summarize_patients
patient_summaries, metadata = summarize_patients(notes, return_metadata=True)

[2026-02-02 19:40:24] INFO __init__.py:87: Extracting relevant patient sentences from 35 notes.
/home/sabrina/mmai-package/src/mmai/patients/tagging.py:184: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["note_date"] = pd.to_datetime(df["note_date"])
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
[2026-02-02 19:40:29] INFO __init__.py:92: Extracted relevant text for 12 patients.

INFO 02-02 19:40:30 [utils.py:261] non-default args: {'max_model_len': 120000, 'disable_log_stats': True, 'model': 'openai/gpt-oss-120b'}
INFO 02-02 19:40:30 [model.py:541] Resolved architecture: GptOssForCausalLM

Parse safetensors files: 100%|██████████| 15/15 [00:00<00:00, 41.68it/s]

INFO 02-02 19:40:31 [model.py:1561] Using max model len 120000
INFO 02-02 19:40:31 [scheduler.py:226] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 02-02 19:40:31 [config.py:314] Overriding max cuda graph capture size to 1024 for performance.

(EngineCore_DP0 pid=34105) INFO 02-02 19:40:38 [core.py:96] Initializing a V1 LLM engine (v0.15.0) with config: model='openai/gpt-oss-120b', speculative_config=None, tokenizer='openai/gpt-oss-120b', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=120000, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=mxfp4, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='openai_gptoss', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=openai/gpt-oss-120b, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer'], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': True, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': True}, 'local_cache_dir': None}
(EngineCore_DP0 pid=34105) INFO 02-02 19:40:39 [parallel_state.py:1212] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.128.0.4:51641 backend=nccl
(EngineCore_DP0 pid=34105) INFO 02-02 19:40:39 [parallel_state.py:1423] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank 0
(EngineCore_DP0 pid=34105) INFO 02-02 19:40:40 [gpu_model_runner.py:4021] Starting to load model openai/gpt-oss-120b...

(EngineCore_DP0 pid=34105) /home/sabrina/mmai-package/.venv/lib/python3.13/site-packages/tvm_ffi/_optional_torch_c_dlpack.py:174: UserWarning: Failed to JIT torch c dlpack extension, EnvTensorAllocator will not be enabled.
(EngineCore_DP0 pid=34105) We recommend installing via `pip install torch-c-dlpack-ext`
(EngineCore_DP0 pid=34105)   warnings.warn(

(EngineCore_DP0 pid=34105) INFO 02-02 19:40:40 [cuda.py:364] Using TRITON_ATTN attention backend out of potential backends: ('TRITON_ATTN',)
(EngineCore_DP0 pid=34105) INFO 02-02 19:40:40 [mxfp4.py:161] Using Marlin backend

Loading safetensors checkpoint shards:   0% Completed | 0/15 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   7% Completed | 1/15 [00:01<00:17,  1.27s/it]
Loading safetensors checkpoint shards:  13% Completed | 2/15 [00:02<00:15,  1.22s/it]
Loading safetensors checkpoint shards:  20% Completed | 3/15 [00:03<00:15,  1.26s/it]
Loading safetensors checkpoint shards:  27% Completed | 4/15 [00:04<00:13,  1.23s/it]
Loading safetensors checkpoint shards:  33% Completed | 5/15 [00:06<00:12,  1.21s/it]
Loading safetensors checkpoint shards:  40% Completed | 6/15 [00:07<00:10,  1.19s/it]
Loading safetensors checkpoint shards:  47% Completed | 7/15 [00:08<00:09,  1.23s/it]
Loading safetensors checkpoint shards:  53% Completed | 8/15 [00:09<00:08,  1.22s/it]
Loading safetensors checkpoint shards:  60% Completed | 9/15 [00:10<00:07,  1.21s/it]
Loading safetensors checkpoint shards:  67% Completed | 10/15 [00:12<00:05,  1.19s/it]
Loading safetensors checkpoint shards:  73% Completed | 11/15 [00:13<00:04,  1.23s/it]
Loading safetensors checkpoint shards:  80% Completed | 12/15 [00:14<00:03,  1.26s/it]
Loading safetensors checkpoint shards:  87% Completed | 13/15 [00:16<00:02,  1.27s/it]
Loading safetensors checkpoint shards:  93% Completed | 14/15 [00:17<00:01,  1.28s/it]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [00:18<00:00,  1.25s/it]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [00:18<00:00,  1.24s/it]
(EngineCore_DP0 pid=34105)

(EngineCore_DP0 pid=34105) INFO 02-02 19:41:00 [default_loader.py:291] Loading weights took 18.59 seconds
(EngineCore_DP0 pid=34105) WARNING 02-02 19:41:00 [marlin_utils_fp4.py:336] Your GPU does not have native support for FP4 computation but FP4 quantization is being used. Weight-only FP4 compression will be used leveraging the Marlin kernel. This may degrade performance for compute-heavy workloads.
(EngineCore_DP0 pid=34105) INFO 02-02 19:41:04 [gpu_model_runner.py:4118] Model loading took 65.97 GiB memory and 22.954570 seconds
(EngineCore_DP0 pid=34105) INFO 02-02 19:41:14 [backends.py:805] Using cache directory: /home/sabrina/.cache/vllm/torch_compile_cache/8d36d9b276/rank_0_0/backbone for vLLM's torch.compile
(EngineCore_DP0 pid=34105) INFO 02-02 19:41:14 [backends.py:865] Dynamo bytecode transform time: 9.61 s
(EngineCore_DP0 pid=34105) INFO 02-02 19:41:23 [backends.py:267] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 1.307 s
(EngineCore_DP0 pid=34105) INFO 02-02 19:41:23 [monitor.py:34] torch.compile takes 10.92 s in total
(EngineCore_DP0 pid=34105) INFO 02-02 19:41:24 [gpu_worker.py:356] Available KV cache memory: 3.34 GiB
(EngineCore_DP0 pid=34105) INFO 02-02 19:41:24 [kv_cache_utils.py:1307] GPU KV cache size: 48,688 tokens
(EngineCore_DP0 pid=34105) INFO 02-02 19:41:24 [kv_cache_utils.py:1312] Maximum concurrency for 120,000 tokens per request: 0.76x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 83/83 [00:09<00:00,  8.82it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:03<00:00,  8.93it/s]

(EngineCore_DP0 pid=34105) INFO 02-02 19:41:39 [gpu_model_runner.py:5051] Graph capturing finished in 14 secs, took 1.12 GiB
(EngineCore_DP0 pid=34105) INFO 02-02 19:41:39 [core.py:272] init engine (profile, create kv cache, warmup model) took 35.02 seconds
(EngineCore_DP0 pid=34105) INFO 02-02 19:41:41 [vllm.py:624] Asynchronous scheduling is enabled.
INFO 02-02 19:41:41 [llm.py:343] Supported tasks: ['generate']

Adding requests: 100%|██████████| 12/12 [00:00<00:00, 129.86it/s]
Processed prompts: 100%|██████████| 12/12 [00:23<00:00,  2.00s/it, est. speed input: 1086.51 toks/s, output: 564.40 toks/s]
[rank0]:[W202 19:42:06.189161718 ProcessGroupNCCL.cpp:1524] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
[2026-02-02 19:42:06] INFO __init__.py:97: Patient summarization complete. Produced 12 rows.

### View results

In [33]:
patient_summaries.head()

,patient_id,cancer_history_summary,general_exclusion_criteria_evidence
0,-12,Age: 19 \nSex: Male \nCancer type: Osteosarc...,No documentation of uncontrolled brain metasta...
1,-11,Age: 68 \nSex: Male \n\nCancer type: Cutaneo...,No evidence of uncontrolled brain metastases. ...
2,-10,Age: 55 \nSex: Female \nCancer type: Ovarian...,No evidence of uncontrolled brain metastases. ...
3,-9,Age: 45 \nSex: Male \nCancer type: T‑cell ly...,Evidence of liver dysfunction – grade 3 transa...
4,-8,Age: 76 \nSex: Female \nCancer type: Ovarian...,"No evidence of uncontrolled brain metastases, ..."

Metadata contains a snapshot of the config used and metadata on the models used.

In [29]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'backend': 'local',
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'trial': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 10000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n'},
  'patient': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 120000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.2},
   'prompt_files': {'primer': 'patient.user.primer.txt',
    'question': 'patient.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n',
   'text_token_threshold': 115000,
   'tagger': {'model_name': 'ksg-dfci/TinyBertOncoTagger-1225',
    'device': 'cuda',
    'batch_size': 1024,
    'positive_tag_cutoff': 0.1,
    'negative_tag_cutoff': 0.9}}},
 'model_metadata': {'patient_tagger': {'model_name': 'ksg-dfci/TinyBertOncoTagger-1225',
   'model_sha': 'f776e1156bd881fb3a976e05c42442a147ddb324',
   'created_at': '2025-09-16T15:06:51+00:00',
   'last_modified': '2025-12-09T20:44:46+00:00'},
  'patient_summarizer': {'model_name': 'openai/gpt-oss-120b',
   'model_sha': 'b5c939de8f754692c1647ca79fbf85e8c1e70f8a',
   'created_at': '2025-08-04T22:33:06+00:00',
   'last_modified': '2025-08-26T17:25:03+00:00'}}}

Save example results

In [30]:
patient_summaries.to_csv('output/patient_summaries.csv', index = None)
with open("output/patient_summarization_metadata.json", "w") as f:
    json.dump(metadata, f, indent=2)

### Generate QC report

In [31]:
from mmai.qc.patients import patient_qc_report
qc_df = patient_qc_report(patient_summaries)
qc_df

                                        metric  value  percent   ids
0                patients_with_no_tagged_notes    NaN      NaN  None
1                   patients_missing_summaries    0.0      0.0    []
2          patients_summary_equals_boilerplate    0.0      0.0    []
3                 patients_missing_keyword:Age    0.0      0.0    []
4                 patients_missing_keyword:Sex    0.0      0.0    []
5         patients_missing_keyword:Cancer type    0.0      0.0    []
6           patients_missing_keyword:Histology    0.0      0.0    []
7      patients_missing_keyword:Current extent    0.0      0.0    []
8          patients_missing_keyword:Biomarkers    0.0      0.0    []
9   patients_missing_keyword:Treatment history    0.0      0.0    []
10          patient_summaries_excessive_length    0.0      0.0    []

### Run tagging and summarization steps separately

Patient summarization is made of two main steps, extraction of relevant sentences and subsequent summarization of those sentences. Below we show how you can run those two steps separately rather than together via `summarize_patients(...)`

#### (1/2) Extract relevant sentences

In [34]:
# import and run function on synthetic patient notes
from mmai.patients.tagging import extract_relevant_sentences
relevant_text, metadata = extract_relevant_sentences(notes)

/home/sabrina/mmai-package/src/mmai/patients/tagging.py:184: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["note_date"] = pd.to_datetime(df["note_date"])
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda

##### View results

In [35]:
relevant_text.head()

   patient_id                                  patient_long_text
0         -12  2025-06-22 progress_notesbase **Oncology Progr...
1         -11  2025-06-22 progress_notesbase **Oncology Progr...
2         -10  2025-06-22 Imaging **PATIENT:** Susan Patel **...
3          -9  2025-06-20 Imaging **Imaging Report – Positron...
4          -8  2025-06-20 progress_notesbase **Oncology Follo...

Metadata contains a snapshot of the config used and metadata on the model used.

In [36]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'backend': 'local',
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'trial': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 10000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n'},
  'patient': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 120000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.2},
   'prompt_files': {'primer': 'patient.user.primer.txt',
    'question': 'patient.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n',
   'text_token_threshold': 115000,
   'tagger': {'model_name': 'ksg-dfci/TinyBertOncoTagger-1225',
    'device': 'cuda',
    'batch_size': 1024,
    'positive_tag_cutoff': 0.1,
    'negative_tag_cutoff': 0.9}}},
 'model_metadata': {'model_name': 'ksg-dfci/TinyBertOncoTagger-1225',
  'model_sha': 'f776e1156bd881fb3a976e05c42442a147ddb324',
  'created_at': '2025-09-16T15:06:51+00:00',
  'last_modified': '2025-12-09T20:44:46+00:00'}}

#### (2/2) Summarize relevant sentences

In [37]:
from mmai.patients.summarize import summarize_from_relevant_sentences
summaries, metadata = summarize_from_relevant_sentences(relevant_text)

INFO 02-02 19:43:35 [utils.py:261] non-default args: {'max_model_len': 120000, 'disable_log_stats': True, 'model': 'openai/gpt-oss-120b'}
INFO 02-02 19:43:35 [model.py:541] Resolved architecture: GptOssForCausalLM

Parse safetensors files: 100%|██████████| 15/15 [00:00<00:00, 38.83it/s]

INFO 02-02 19:43:36 [model.py:1561] Using max model len 120000
INFO 02-02 19:43:36 [scheduler.py:226] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 02-02 19:43:36 [config.py:314] Overriding max cuda graph capture size to 1024 for performance.

(EngineCore_DP0 pid=36424) INFO 02-02 19:43:43 [core.py:96] Initializing a V1 LLM engine (v0.15.0) with config: model='openai/gpt-oss-120b', speculative_config=None, tokenizer='openai/gpt-oss-120b', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=120000, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=mxfp4, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='openai_gptoss', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=openai/gpt-oss-120b, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer'], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': True, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': True}, 'local_cache_dir': None}
(EngineCore_DP0 pid=36424) INFO 02-02 19:43:44 [parallel_state.py:1212] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.128.0.4:59087 backend=nccl
(EngineCore_DP0 pid=36424) INFO 02-02 19:43:44 [parallel_state.py:1423] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank 0
(EngineCore_DP0 pid=36424) INFO 02-02 19:43:45 [gpu_model_runner.py:4021] Starting to load model openai/gpt-oss-120b...

(EngineCore_DP0 pid=36424) /home/sabrina/mmai-package/.venv/lib/python3.13/site-packages/tvm_ffi/_optional_torch_c_dlpack.py:174: UserWarning: Failed to JIT torch c dlpack extension, EnvTensorAllocator will not be enabled.
(EngineCore_DP0 pid=36424) We recommend installing via `pip install torch-c-dlpack-ext`
(EngineCore_DP0 pid=36424)   warnings.warn(

(EngineCore_DP0 pid=36424) INFO 02-02 19:43:46 [cuda.py:364] Using TRITON_ATTN attention backend out of potential backends: ('TRITON_ATTN',)
(EngineCore_DP0 pid=36424) INFO 02-02 19:43:46 [mxfp4.py:161] Using Marlin backend

Loading safetensors checkpoint shards:   0% Completed | 0/15 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   7% Completed | 1/15 [00:01<00:17,  1.27s/it]
Loading safetensors checkpoint shards:  13% Completed | 2/15 [00:02<00:15,  1.22s/it]
Loading safetensors checkpoint shards:  20% Completed | 3/15 [00:03<00:15,  1.26s/it]
Loading safetensors checkpoint shards:  27% Completed | 4/15 [00:04<00:13,  1.23s/it]
Loading safetensors checkpoint shards:  33% Completed | 5/15 [00:06<00:12,  1.21s/it]
Loading safetensors checkpoint shards:  40% Completed | 6/15 [00:07<00:10,  1.19s/it]
Loading safetensors checkpoint shards:  47% Completed | 7/15 [00:08<00:09,  1.23s/it]
Loading safetensors checkpoint shards:  53% Completed | 8/15 [00:09<00:08,  1.21s/it]
Loading safetensors checkpoint shards:  60% Completed | 9/15 [00:10<00:07,  1.20s/it]
Loading safetensors checkpoint shards:  67% Completed | 10/15 [00:12<00:05,  1.18s/it]
Loading safetensors checkpoint shards:  73% Completed | 11/15 [00:13<00:04,  1.21s/it]
Loading safetensors checkpoint shards:  80% Completed | 12/15 [00:14<00:03,  1.24s/it]
Loading safetensors checkpoint shards:  87% Completed | 13/15 [00:15<00:02,  1.26s/it]
Loading safetensors checkpoint shards:  93% Completed | 14/15 [00:17<00:01,  1.27s/it]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [00:18<00:00,  1.24s/it]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [00:18<00:00,  1.23s/it]
(EngineCore_DP0 pid=36424)

(EngineCore_DP0 pid=36424) INFO 02-02 19:44:05 [default_loader.py:291] Loading weights took 18.48 seconds
(EngineCore_DP0 pid=36424) WARNING 02-02 19:44:05 [marlin_utils_fp4.py:336] Your GPU does not have native support for FP4 computation but FP4 quantization is being used. Weight-only FP4 compression will be used leveraging the Marlin kernel. This may degrade performance for compute-heavy workloads.
(EngineCore_DP0 pid=36424) INFO 02-02 19:44:09 [gpu_model_runner.py:4118] Model loading took 65.97 GiB memory and 22.876470 seconds
(EngineCore_DP0 pid=36424) INFO 02-02 19:44:18 [backends.py:805] Using cache directory: /home/sabrina/.cache/vllm/torch_compile_cache/8d36d9b276/rank_0_0/backbone for vLLM's torch.compile
(EngineCore_DP0 pid=36424) INFO 02-02 19:44:18 [backends.py:865] Dynamo bytecode transform time: 9.39 s
(EngineCore_DP0 pid=36424) INFO 02-02 19:44:28 [backends.py:267] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 1.332 s
(EngineCore_DP0 pid=36424) INFO 02-02 19:44:28 [monitor.py:34] torch.compile takes 10.72 s in total
(EngineCore_DP0 pid=36424) INFO 02-02 19:44:29 [gpu_worker.py:356] Available KV cache memory: 3.34 GiB
(EngineCore_DP0 pid=36424) INFO 02-02 19:44:29 [kv_cache_utils.py:1307] GPU KV cache size: 48,688 tokens
(EngineCore_DP0 pid=36424) INFO 02-02 19:44:29 [kv_cache_utils.py:1312] Maximum concurrency for 120,000 tokens per request: 0.76x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 83/83 [00:09<00:00,  8.87it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:03<00:00,  8.78it/s]

(EngineCore_DP0 pid=36424) INFO 02-02 19:44:43 [gpu_model_runner.py:5051] Graph capturing finished in 14 secs, took 1.12 GiB
(EngineCore_DP0 pid=36424) INFO 02-02 19:44:43 [core.py:272] init engine (profile, create kv cache, warmup model) took 34.91 seconds
(EngineCore_DP0 pid=36424) INFO 02-02 19:44:46 [vllm.py:624] Asynchronous scheduling is enabled.
INFO 02-02 19:44:46 [llm.py:343] Supported tasks: ['generate']

Adding requests: 100%|██████████| 12/12 [00:00<00:00, 134.99it/s]
Processed prompts: 100%|██████████| 12/12 [00:27<00:00,  2.31s/it, est. speed input: 939.04 toks/s, output: 504.38 toks/s]
[rank0]:[W202 19:45:14.717778478 ProcessGroupNCCL.cpp:1524] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

##### View results

In [38]:
summaries.head()

,patient_id,cancer_history_summary,general_exclusion_criteria_evidence
0,-12,Age: 19 \nSex: Male \n\nCancer type: Osteosa...,"No evidence of uncontrolled brain metastases, ..."
1,-11,Age: 68 \nSex: Male \n\nCancer type: Cutaneo...,"No evidence of uncontrolled brain metastases, ..."
2,-10,Age: 55 \nSex: Female \nCancer type: Ovarian...,"No evidence of uncontrolled brain metastases, ..."
3,-9,Age: 45 \nSex: Male \nCancer type: T‑cell ly...,Evidence of liver dysfunction – Grade 3 transa...
4,-8,Age: 76 \nSex: Female \nCancer type: Ovarian...,No evidence of uncontrolled brain metastases (...

Metadata contains a snapshot of the config used and metadata on the model used.

In [39]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'backend': 'local',
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'trial': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 10000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n'},
  'patient': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 120000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.2},
   'prompt_files': {'primer': 'patient.user.primer.txt',
    'question': 'patient.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n',
   'text_token_threshold': 115000,
   'tagger': {'model_name': 'ksg-dfci/TinyBertOncoTagger-1225',
    'device': 'cuda',
    'batch_size': 1024,
    'positive_tag_cutoff': 0.1,
    'negative_tag_cutoff': 0.9}}},
 'model_metadata': {'model_name': 'openai/gpt-oss-120b',
  'model_sha': 'b5c939de8f754692c1647ca79fbf85e8c1e70f8a',
  'created_at': '2025-08-04T22:33:06+00:00',
  'last_modified': '2025-08-26T17:25:03+00:00'}}

#### Generate QC report

In [40]:
from mmai.qc.patients import patient_qc_report
qc_df = patient_qc_report(summaries, tagged_patients=relevant_text)
qc_df

                                        metric  value  percent ids
0                patients_with_no_tagged_notes      0      0.0  []
1                   patients_missing_summaries      0      0.0  []
2          patients_summary_equals_boilerplate      0      0.0  []
3                 patients_missing_keyword:Age      0      0.0  []
4                 patients_missing_keyword:Sex      0      0.0  []
5         patients_missing_keyword:Cancer type      0      0.0  []
6           patients_missing_keyword:Histology      0      0.0  []
7      patients_missing_keyword:Current extent      0      0.0  []
8          patients_missing_keyword:Biomarkers      0      0.0  []
9   patients_missing_keyword:Treatment history      0      0.0  []
10          patient_summaries_excessive_length      0      0.0  []