In [1]:
# general imports
import pandas as pd

# MMAI Examples

## Trial Summarization

### Read in data

In [2]:
trials_path = "data/scheduled__2025-09-04T230000+0000.trials_for_summarize.csv"
trials = pd.read_csv(trials_path)

### Convert column names to those expected by the function.
- `trial_id`
- `trial_title`
- `brief_summary`
- `eligibility_criteria`

In [3]:
trials.rename(columns={"title": "trial_title", "nct_id": "trial_id"}, inplace=True)

### Run `summarize_trials` function.

*Note: You can turn debug mode on to add intermediate summarization outputs to the dataframe. Example below*
```python
from mmai import load_preset
config = load_preset("default")
config.debug_mode = True
df, metadata = summarize_trials(trials, config=config, return_metadata=True)
```

In [ ]:
# import and run function on trial data
from mmai.trials import summarize_trials

trial_results, metadata, qc_report = summarize_trials(
    trials, return_metadata=True, return_qc=True
)

/home/sabrina/mmai-package/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

INFO 02-23 18:15:06 [utils.py:261] non-default args: {'max_model_len': 10000, 'disable_log_stats': True, 'model': 'openai/gpt-oss-120b'}
INFO 02-23 18:15:06 [model.py:541] Resolved architecture: GptOssForCausalLM

Parse safetensors files: 100%|██████████| 15/15 [00:01<00:00, 13.45it/s]

INFO 02-23 18:15:08 [model.py:1561] Using max model len 10000

2026-02-23 18:15:10,341	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.

INFO 02-23 18:15:10 [scheduler.py:226] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 02-23 18:15:10 [config.py:314] Overriding max cuda graph capture size to 1024 for performance.
INFO 02-23 18:15:10 [vllm.py:624] Asynchronous scheduling is enabled.
(EngineCore_DP0 pid=14641) INFO 02-23 18:15:12 [core.py:96] Initializing a V1 LLM engine (v0.15.1) with config: model='openai/gpt-oss-120b', speculative_config=None, tokenizer='openai/gpt-oss-120b', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=10000, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=mxfp4, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='openai_gptoss', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=openai/gpt-oss-120b, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update'], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': True, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': True}, 'local_cache_dir': None, 'static_all_moe_layers': []}
(EngineCore_DP0 pid=14641) INFO 02-23 18:15:12 [parallel_state.py:1212] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.128.0.4:52439 backend=nccl
(EngineCore_DP0 pid=14641) INFO 02-23 18:15:12 [parallel_state.py:1423] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
(EngineCore_DP0 pid=14641) INFO 02-23 18:15:13 [gpu_model_runner.py:4033] Starting to load model openai/gpt-oss-120b...

(EngineCore_DP0 pid=14641) /home/sabrina/mmai-package/.venv/lib/python3.13/site-packages/tvm_ffi/_optional_torch_c_dlpack.py:174: UserWarning: Failed to JIT torch c dlpack extension, EnvTensorAllocator will not be enabled.
(EngineCore_DP0 pid=14641) We recommend installing via `pip install torch-c-dlpack-ext`
(EngineCore_DP0 pid=14641)   warnings.warn(

(EngineCore_DP0 pid=14641) INFO 02-23 18:15:14 [cuda.py:364] Using TRITON_ATTN attention backend out of potential backends: ('TRITON_ATTN',)
(EngineCore_DP0 pid=14641) INFO 02-23 18:15:14 [mxfp4.py:161] Using Marlin backend

Loading safetensors checkpoint shards:   0% Completed | 0/15 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   7% Completed | 1/15 [00:15<03:40, 15.72s/it]
Loading safetensors checkpoint shards:  13% Completed | 2/15 [00:29<03:11, 14.73s/it]
Loading safetensors checkpoint shards:  20% Completed | 3/15 [00:45<03:02, 15.20s/it]
Loading safetensors checkpoint shards:  27% Completed | 4/15 [00:59<02:42, 14.74s/it]
Loading safetensors checkpoint shards:  33% Completed | 5/15 [01:13<02:24, 14.41s/it]
Loading safetensors checkpoint shards:  40% Completed | 6/15 [01:27<02:08, 14.22s/it]
Loading safetensors checkpoint shards:  47% Completed | 7/15 [01:42<01:57, 14.72s/it]
Loading safetensors checkpoint shards:  53% Completed | 8/15 [01:57<01:41, 14.50s/it]
Loading safetensors checkpoint shards:  60% Completed | 9/15 [02:11<01:26, 14.41s/it]
Loading safetensors checkpoint shards:  67% Completed | 10/15 [02:25<01:11, 14.29s/it]
Loading safetensors checkpoint shards:  73% Completed | 11/15 [02:41<00:58, 14.74s/it]
Loading safetensors checkpoint shards:  80% Completed | 12/15 [02:56<00:45, 15.05s/it]
Loading safetensors checkpoint shards:  87% Completed | 13/15 [03:12<00:30, 15.27s/it]
Loading safetensors checkpoint shards:  93% Completed | 14/15 [03:28<00:15, 15.42s/it]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [03:42<00:00, 15.00s/it]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [03:42<00:00, 14.82s/it]
(EngineCore_DP0 pid=14641)

(EngineCore_DP0 pid=14641) INFO 02-23 18:18:57 [default_loader.py:291] Loading weights took 222.45 seconds
(EngineCore_DP0 pid=14641) WARNING 02-23 18:18:57 [marlin_utils_fp4.py:336] Your GPU does not have native support for FP4 computation but FP4 quantization is being used. Weight-only FP4 compression will be used leveraging the Marlin kernel. This may degrade performance for compute-heavy workloads.
(EngineCore_DP0 pid=14641) INFO 02-23 18:19:01 [gpu_model_runner.py:4130] Model loading took 65.97 GiB memory and 226.775271 seconds
(EngineCore_DP0 pid=14641) INFO 02-23 18:19:10 [backends.py:812] Using cache directory: /home/sabrina/.cache/vllm/torch_compile_cache/c73021c267/rank_0_0/backbone for vLLM's torch.compile
(EngineCore_DP0 pid=14641) INFO 02-23 18:19:10 [backends.py:872] Dynamo bytecode transform time: 8.55 s
(EngineCore_DP0 pid=14641) INFO 02-23 18:19:16 [backends.py:267] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 1.398 s
(EngineCore_DP0 pid=14641) INFO 02-23 18:19:16 [monitor.py:34] torch.compile takes 9.94 s in total
(EngineCore_DP0 pid=14641) INFO 02-23 18:19:18 [gpu_worker.py:356] Available KV cache memory: 3.34 GiB
(EngineCore_DP0 pid=14641) INFO 02-23 18:19:18 [kv_cache_utils.py:1307] GPU KV cache size: 48,688 tokens
(EngineCore_DP0 pid=14641) INFO 02-23 18:19:18 [kv_cache_utils.py:1312] Maximum concurrency for 10,000 tokens per request: 5.31x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 83/83 [00:08<00:00,  9.81it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:03<00:00,  9.69it/s]

(EngineCore_DP0 pid=14641) INFO 02-23 18:19:31 [gpu_model_runner.py:5063] Graph capturing finished in 13 secs, took 1.12 GiB
(EngineCore_DP0 pid=14641) INFO 02-23 18:19:31 [core.py:272] init engine (profile, create kv cache, warmup model) took 29.57 seconds
INFO 02-23 18:19:33 [llm.py:343] Supported tasks: ['generate']

Adding requests: 100%|██████████| 470/470 [00:03<00:00, 149.95it/s]
Processed prompts:  41%|████▏     | 195/470 [07:04<06:14,  1.36s/it, est. speed input: 1114.90 toks/s, output: 831.80 toks/s]

### View results

In [5]:
trial_results.head()

,trial_id,clinical_space_number,clinical_space_summary,general_exclusion_criteria,space_trial_id
0,NCT03319901,1,Age range allowed: ≥60 years. Sex allowed: Mal...,Pregnancy or lactating women; inability to use...,NCT03319901-1
1,NCT03319901,2,Age range allowed: ≥18 years. Sex allowed: Mal...,Pregnancy or lactating women; inability to use...,NCT03319901-2
2,NCT04792489,1,Age range allowed: ≥18 years. Sex allowed: Mal...,Inability to give informed consent. Current HI...,NCT04792489-1
3,NCT04792489,2,Age range allowed: ≥18 years. Sex allowed: Mal...,Inability to give informed consent. Current HI...,NCT04792489-2
4,NCT04792489,3,Age range allowed: ≥18 years. Sex allowed: Mal...,Inability to give informed consent. Current HI...,NCT04792489-3

Metadata contains a snapshot of the config used and metadata on the model used.

In [6]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'backend': 'local',
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'trial': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 10000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n'},
  'patient': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 120000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.2},
   'prompt_files': {'primer': 'patient.user.primer.txt',
    'question': 'patient.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n',
   'text_token_threshold': 115000,
   'tagger': {'model_name': 'ksg-dfci/TinyBertOncoTagger-1225',
    'device': 'cuda',
    'batch_size': 1024,
    'positive_tag_cutoff': 0.1,
    'negative_tag_cutoff': 0.9}},
  'embedding': {'model_path': 'ksg-dfci/TrialSpace-1225',
   'device': 'cpu',
   'prompt_file': 'embedding.txt'}},
 'model_metadata': {'trial_summarizer': {'model_name': 'openai/gpt-oss-120b',
   'model_sha': 'b5c939de8f754692c1647ca79fbf85e8c1e70f8a',
   'created_at': '2025-08-04T22:33:06+00:00',
   'last_modified': '2025-08-26T17:25:03+00:00'}}}

QC report on the trial summarization run

In [7]:
qc_report

,metric,value,percent,ids
0,trials_missing_in_output,4.0,0.851064,"[NCT04139902, NCT04906902, NCT06435429, NCT064..."
1,trials_truncated_llm_response,1.0,0.212766,[NCT04771572]
2,spaces_exceed_embedding_token_limit,0.0,0.000000,[]
3,spaces_per_trial_min,1.0,NaN,[]
4,spaces_per_trial_median,2.0,NaN,[]
5,spaces_per_trial_max,44.0,NaN,[]
6,trials_with_non_distinct_spaces,6.0,1.276596,"[NCT03260491, NCT04389632, NCT05536141, NCT055..."
7,spaces_dropped_missing_keyword:Age,0.0,0.000000,[]
8,spaces_dropped_missing_keyword:Sex,0.0,0.000000,[]
9,spaces_dropped_missing_keyword:Cancer type,0.0,0.000000,[]
10,spaces_dropped_missing_keyword:Histology,0.0,0.000000,[]
11,spaces_dropped_missing_keyword:Cancer burden,0.0,0.000000,[]
12,spaces_dropped_missing_keyword:Prior treatment...,2.0,0.137268,"[NCT04771572-28, NCT06479135-3]"
13,spaces_dropped_missing_keyword:Prior treatment...,3.0,0.205903,"[NCT04771572-28, NCT04906902-1, NCT06479135-3]"
14,spaces_dropped_missing_keyword:Biomarkers requ...,5.0,0.343171,"[NCT04139902-1, NCT04771572-28, NCT04906902-1,..."
15,spaces_dropped_missing_keyword:Biomarkers excl...,6.0,0.411805,"[NCT04771572-28, NCT04906902-1, NCT06435429-1,..."
16,trials_exclusion_criteria_not_extracted,9.0,1.914894,"[NCT03564340, NCT04150497, NCT04771572, NCT048..."

Save example results

In [13]:
import json

trial_results.to_csv("output/trial_summaries.csv", index=None)
with open("output/trial_summarization_metadata.json", "w") as f:
    json.dump(metadata, f, indent=2)
qc_report.to_csv("output/trial_qc_report.csv", index=None)

## Patient summarization

### Read in data

In [14]:
notes_path = "data/2026_01_16_dummy_notes.csv"
notes = pd.read_csv(notes_path)
notes.head()

,DFCI_MRN,EVENT_DATE,RPT_TEXT,NOTE_SOURCE,LAST_MOD,PROVIDER_TYPE,RPT_STATUS,ENCOUNTER_TYPE_DESC,PROVIDER_DEPT,PROC_DESC
0,-1,6/20/25,**Imaging Report**\n\n---\n\n**Patient:** Mich...,Imaging,6/25/25,PROVIDER_TYPE_NM,NOTE_STATUS_DESCR,ENCOUNTER_TYPE_DESCR,NaN,NaN
1,-1,6/25/25,**Oncology Progress Note – Follow‑Up Visit**\n...,progress_notesbase,6/25/25,Physician,Signed,Office Visit,NaN,NaN
2,-2,6/19/25,**Imaging Report**\n\n**Patient:** Daniel O’Co...,Imaging,6/25/25,PROVIDER_TYPE_NM,NOTE_STATUS_DESCR,ENCOUNTER_TYPE_DESCR,NaN,NaN
3,-2,6/20/25,**Oncology Progress Note**\n\n**Patient:** Dan...,progress_notesbase,6/25/25,Physician,Signed,Office Visit,NaN,NaN
4,-2,6/25/25,**Oncology Progress Note – Follow‑up Visit**\n...,progress_notesbase,6/25/25,Physician,Signed,Office Visit,NaN,NaN

### Convert column names to those expected by the function.
- `patient_id`
- `note_text`
- `note_type`
- `note_date`

In [15]:
notes.rename(
    columns={
        "DFCI_MRN": "patient_id",
        "RPT_TEXT": "note_text",
        "NOTE_SOURCE": "note_type",
        "EVENT_DATE": "note_date",
    },
    inplace=True,
)

### Run patient summarization

*Note: You can turn debug mode on to add intermediate summarization outputs to the dataframe. Example below*
```python
from mmai import load_preset
config = load_preset("default")
config.debug_mode = True
df, metadata = summarize_patients(notes, config=config, return_metadata=True)
```

In [22]:
from mmai.patients import summarize_patients

patient_summaries, metadata, qc_report = summarize_patients(
    notes, return_metadata=True, return_qc=True
)

[2026-02-17 17:33:47] INFO __init__.py:107: Extracting relevant patient sentences from 35 notes.
/home/sabrina/mmai-package/src/mmai/patients/tagging.py:190: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["note_date"] = pd.to_datetime(df["note_date"])
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
[2026-02-17 17:33:52] INFO __init__.py:116: Extracted relevant text for 12 patients.

INFO 02-17 17:33:53 [utils.py:261] non-default args: {'max_model_len': 120000, 'disable_log_stats': True, 'model': 'openai/gpt-oss-120b'}
INFO 02-17 17:33:54 [model.py:541] Resolved architecture: GptOssForCausalLM

Parse safetensors files: 100%|██████████| 15/15 [00:00<00:00, 133.20it/s]

INFO 02-17 17:33:54 [model.py:1561] Using max model len 120000
INFO 02-17 17:33:54 [scheduler.py:226] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 02-17 17:33:54 [config.py:314] Overriding max cuda graph capture size to 1024 for performance.

(EngineCore_DP0 pid=29138) INFO 02-17 17:34:02 [core.py:96] Initializing a V1 LLM engine (v0.15.1) with config: model='openai/gpt-oss-120b', speculative_config=None, tokenizer='openai/gpt-oss-120b', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=120000, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=mxfp4, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='openai_gptoss', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=openai/gpt-oss-120b, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update'], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': True, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': True}, 'local_cache_dir': None, 'static_all_moe_layers': []}
(EngineCore_DP0 pid=29138) INFO 02-17 17:34:03 [parallel_state.py:1212] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.128.0.4:42641 backend=nccl
(EngineCore_DP0 pid=29138) INFO 02-17 17:34:03 [parallel_state.py:1423] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank 0
(EngineCore_DP0 pid=29138) INFO 02-17 17:34:03 [gpu_model_runner.py:4033] Starting to load model openai/gpt-oss-120b...

(EngineCore_DP0 pid=29138) /home/sabrina/mmai-package/.venv/lib/python3.13/site-packages/tvm_ffi/_optional_torch_c_dlpack.py:174: UserWarning: Failed to JIT torch c dlpack extension, EnvTensorAllocator will not be enabled.
(EngineCore_DP0 pid=29138) We recommend installing via `pip install torch-c-dlpack-ext`
(EngineCore_DP0 pid=29138)   warnings.warn(

(EngineCore_DP0 pid=29138) INFO 02-17 17:34:04 [cuda.py:364] Using TRITON_ATTN attention backend out of potential backends: ('TRITON_ATTN',)
(EngineCore_DP0 pid=29138) INFO 02-17 17:34:04 [mxfp4.py:161] Using Marlin backend

Loading safetensors checkpoint shards:   0% Completed | 0/15 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   7% Completed | 1/15 [00:01<00:17,  1.28s/it]
Loading safetensors checkpoint shards:  13% Completed | 2/15 [00:02<00:15,  1.23s/it]
Loading safetensors checkpoint shards:  20% Completed | 3/15 [00:03<00:15,  1.27s/it]
Loading safetensors checkpoint shards:  27% Completed | 4/15 [00:04<00:13,  1.23s/it]
Loading safetensors checkpoint shards:  33% Completed | 5/15 [00:06<00:12,  1.21s/it]
Loading safetensors checkpoint shards:  40% Completed | 6/15 [00:07<00:10,  1.19s/it]
Loading safetensors checkpoint shards:  47% Completed | 7/15 [00:08<00:09,  1.23s/it]
Loading safetensors checkpoint shards:  53% Completed | 8/15 [00:09<00:08,  1.21s/it]
Loading safetensors checkpoint shards:  60% Completed | 9/15 [00:10<00:07,  1.20s/it]
Loading safetensors checkpoint shards:  67% Completed | 10/15 [00:12<00:05,  1.20s/it]
Loading safetensors checkpoint shards:  73% Completed | 11/15 [00:13<00:04,  1.23s/it]
Loading safetensors checkpoint shards:  80% Completed | 12/15 [00:14<00:03,  1.26s/it]
Loading safetensors checkpoint shards:  87% Completed | 13/15 [00:16<00:02,  1.28s/it]
Loading safetensors checkpoint shards:  93% Completed | 14/15 [00:17<00:01,  1.29s/it]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [00:18<00:00,  1.26s/it]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [00:18<00:00,  1.24s/it]
(EngineCore_DP0 pid=29138)

(EngineCore_DP0 pid=29138) INFO 02-17 17:34:23 [default_loader.py:291] Loading weights took 18.67 seconds
(EngineCore_DP0 pid=29138) WARNING 02-17 17:34:23 [marlin_utils_fp4.py:336] Your GPU does not have native support for FP4 computation but FP4 quantization is being used. Weight-only FP4 compression will be used leveraging the Marlin kernel. This may degrade performance for compute-heavy workloads.
(EngineCore_DP0 pid=29138) INFO 02-17 17:34:27 [gpu_model_runner.py:4130] Model loading took 65.97 GiB memory and 22.894833 seconds
(EngineCore_DP0 pid=29138) INFO 02-17 17:34:37 [backends.py:812] Using cache directory: /home/sabrina/.cache/vllm/torch_compile_cache/4d643c9beb/rank_0_0/backbone for vLLM's torch.compile
(EngineCore_DP0 pid=29138) INFO 02-17 17:34:37 [backends.py:872] Dynamo bytecode transform time: 8.77 s
(EngineCore_DP0 pid=29138) INFO 02-17 17:34:46 [backends.py:267] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 1.155 s
(EngineCore_DP0 pid=29138) INFO 02-17 17:34:46 [monitor.py:34] torch.compile takes 9.93 s in total
(EngineCore_DP0 pid=29138) INFO 02-17 17:34:47 [gpu_worker.py:356] Available KV cache memory: 3.34 GiB
(EngineCore_DP0 pid=29138) INFO 02-17 17:34:47 [kv_cache_utils.py:1307] GPU KV cache size: 48,688 tokens
(EngineCore_DP0 pid=29138) INFO 02-17 17:34:47 [kv_cache_utils.py:1312] Maximum concurrency for 120,000 tokens per request: 0.76x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 83/83 [00:08<00:00,  9.80it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:03<00:00,  9.84it/s]

(EngineCore_DP0 pid=29138) INFO 02-17 17:35:00 [gpu_model_runner.py:5063] Graph capturing finished in 13 secs, took 1.12 GiB
(EngineCore_DP0 pid=29138) INFO 02-17 17:35:00 [core.py:272] init engine (profile, create kv cache, warmup model) took 32.48 seconds
(EngineCore_DP0 pid=29138) INFO 02-17 17:35:02 [vllm.py:624] Asynchronous scheduling is enabled.
INFO 02-17 17:35:02 [llm.py:343] Supported tasks: ['generate']

Adding requests: 100%|██████████| 12/12 [00:00<00:00, 172.29it/s]
Processed prompts: 100%|██████████| 12/12 [00:24<00:00,  2.04s/it, est. speed input: 1063.77 toks/s, output: 569.90 toks/s]
[rank0]:[W217 17:35:27.616957965 ProcessGroupNCCL.cpp:1524] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
[2026-02-17 17:35:28] INFO __init__.py:126: Patient summarization complete. Produced 12 rows.

### View results

In [23]:
patient_summaries.head()

,patient_id,cancer_history_summary,general_exclusion_criteria_evidence
0,-12,Age: 19 \nSex: Male \n\nCancer type: Osteosa...,"No evidence of uncontrolled brain metastases, ..."
1,-11,Age: 68 \nSex: Male \n\nCancer type: Cutaneo...,No evidence of uncontrolled brain metastases. ...
2,-10,Age: 55 \nSex: Female \n\nCancer type: Ovari...,"No evidence of uncontrolled brain metastases, ..."
3,-9,Age: 45 \nSex: Male \n\nCancer type: T‑cell ...,Evidence of liver dysfunction – transaminitis ...
4,-8,Age: 76 \nSex: Female \nCancer type: Ovarian...,"No evidence of uncontrolled brain metastases, ..."

Metadata contains a snapshot of the config used and metadata on the models used.

In [24]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'backend': 'local',
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'trial': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 10000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n'},
  'patient': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 120000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.2},
   'prompt_files': {'primer': 'patient.user.primer.txt',
    'question': 'patient.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n',
   'text_token_threshold': 115000,
   'tagger': {'model_name': 'ksg-dfci/TinyBertOncoTagger-1225',
    'device': 'cuda',
    'batch_size': 1024,
    'positive_tag_cutoff': 0.1,
    'negative_tag_cutoff': 0.9}},
  'embedding': {'model_path': 'ksg-dfci/TrialSpace-1225',
   'device': 'cpu',
   'prompt_file': 'embedding.txt'}},
 'model_metadata': {'patient_tagger': {'model_name': 'ksg-dfci/TinyBertOncoTagger-1225',
   'model_sha': 'f776e1156bd881fb3a976e05c42442a147ddb324',
   'created_at': '2025-09-16T15:06:51+00:00',
   'last_modified': '2025-12-09T20:44:46+00:00'},
  'patient_summarizer': {'model_name': 'openai/gpt-oss-120b',
   'model_sha': 'b5c939de8f754692c1647ca79fbf85e8c1e70f8a',
   'created_at': '2025-08-04T22:33:06+00:00',
   'last_modified': '2025-08-26T17:25:03+00:00'}}}

QC report on patient summarization

In [25]:
qc_report

                                        metric  value  percent ids
0      patients_dropped_noninformative_summary      0      0.0  []
1              patients_truncated_llm_response      0      0.0  []
2        patients_exceed_embedding_token_limit      0      0.0  []
3    patients_exclusion_criteria_not_extracted      0      0.0  []
4                 patients_missing_keyword:Age      0      0.0  []
5                 patients_missing_keyword:Sex      0      0.0  []
6         patients_missing_keyword:Cancer type      0      0.0  []
7           patients_missing_keyword:Histology      0      0.0  []
8      patients_missing_keyword:Current extent      0      0.0  []
9          patients_missing_keyword:Biomarkers      0      0.0  []
10  patients_missing_keyword:Treatment history      0      0.0  []
11               patients_with_no_tagged_notes      0      0.0  []
12                  patients_missing_summaries      0      0.0  []

Save example results

In [26]:
patient_summaries.to_csv("output/patient_summaries.csv", index=None)
with open("output/patient_summarization_metadata.json", "w") as f:
    json.dump(metadata, f, indent=2)
qc_report.to_csv("output/patient_qc_report.csv", index=None)

### Run tagging and summarization steps separately

Patient summarization is made of two main steps, extraction of relevant sentences and subsequent summarization of those sentences. Below we show how you can run those two steps separately rather than together via `summarize_patients(...)`

#### (1/2) Extract relevant sentences

In [27]:
# import and run function on synthetic patient notes
from mmai.patients.tagging import extract_relevant_sentences

relevant_text, metadata, qc_report = extract_relevant_sentences(notes, return_qc=True)

/home/sabrina/mmai-package/src/mmai/patients/tagging.py:190: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["note_date"] = pd.to_datetime(df["note_date"])
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda

##### View results

In [28]:
relevant_text.head()

   patient_id                                  patient_long_text
0         -12  2025-06-22 progress_notesbase **Oncology Progr...
1         -11  2025-06-22 progress_notesbase **Oncology Progr...
2         -10  2025-06-22 Imaging **PATIENT:** Susan Patel **...
3          -9  2025-06-20 Imaging **Imaging Report – Positron...
4          -8  2025-06-20 progress_notesbase **Oncology Follo...

Metadata contains a snapshot of the config used and metadata on the model used.

In [29]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'backend': 'local',
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'trial': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 10000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n'},
  'patient': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 120000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.2},
   'prompt_files': {'primer': 'patient.user.primer.txt',
    'question': 'patient.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n',
   'text_token_threshold': 115000,
   'tagger': {'model_name': 'ksg-dfci/TinyBertOncoTagger-1225',
    'device': 'cuda',
    'batch_size': 1024,
    'positive_tag_cutoff': 0.1,
    'negative_tag_cutoff': 0.9}},
  'embedding': {'model_path': 'ksg-dfci/TrialSpace-1225',
   'device': 'cpu',
   'prompt_file': 'embedding.txt'}},
 'model_metadata': {'model_name': 'ksg-dfci/TinyBertOncoTagger-1225',
  'model_sha': 'f776e1156bd881fb3a976e05c42442a147ddb324',
  'created_at': '2025-09-16T15:06:51+00:00',
  'last_modified': '2025-12-09T20:44:46+00:00'}}

Tagging step QC report

In [30]:
qc_report

                          metric  value  percent ids
0  patients_with_no_tagged_notes      0      0.0  []

#### (2/2) Summarize relevant sentences

In [31]:
from mmai.patients.summarize import summarize_from_relevant_sentences

summaries, metadata, qc_report = summarize_from_relevant_sentences(
    relevant_text, return_qc=True
)

INFO 02-17 17:35:45 [utils.py:261] non-default args: {'max_model_len': 120000, 'disable_log_stats': True, 'model': 'openai/gpt-oss-120b'}
INFO 02-17 17:35:46 [model.py:541] Resolved architecture: GptOssForCausalLM

Parse safetensors files: 100%|██████████| 15/15 [00:00<00:00, 150.45it/s]

INFO 02-17 17:35:46 [model.py:1561] Using max model len 120000
INFO 02-17 17:35:46 [scheduler.py:226] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 02-17 17:35:46 [config.py:314] Overriding max cuda graph capture size to 1024 for performance.

(EngineCore_DP0 pid=30853) INFO 02-17 17:35:54 [core.py:96] Initializing a V1 LLM engine (v0.15.1) with config: model='openai/gpt-oss-120b', speculative_config=None, tokenizer='openai/gpt-oss-120b', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=120000, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=mxfp4, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='openai_gptoss', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=openai/gpt-oss-120b, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update'], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': True, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': True}, 'local_cache_dir': None, 'static_all_moe_layers': []}
(EngineCore_DP0 pid=30853) INFO 02-17 17:35:55 [parallel_state.py:1212] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.128.0.4:47045 backend=nccl
(EngineCore_DP0 pid=30853) INFO 02-17 17:35:55 [parallel_state.py:1423] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank 0
(EngineCore_DP0 pid=30853) INFO 02-17 17:35:55 [gpu_model_runner.py:4033] Starting to load model openai/gpt-oss-120b...

(EngineCore_DP0 pid=30853) /home/sabrina/mmai-package/.venv/lib/python3.13/site-packages/tvm_ffi/_optional_torch_c_dlpack.py:174: UserWarning: Failed to JIT torch c dlpack extension, EnvTensorAllocator will not be enabled.
(EngineCore_DP0 pid=30853) We recommend installing via `pip install torch-c-dlpack-ext`
(EngineCore_DP0 pid=30853)   warnings.warn(

(EngineCore_DP0 pid=30853) INFO 02-17 17:35:56 [cuda.py:364] Using TRITON_ATTN attention backend out of potential backends: ('TRITON_ATTN',)
(EngineCore_DP0 pid=30853) INFO 02-17 17:35:56 [mxfp4.py:161] Using Marlin backend

Loading safetensors checkpoint shards:   0% Completed | 0/15 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   7% Completed | 1/15 [00:01<00:17,  1.28s/it]
Loading safetensors checkpoint shards:  13% Completed | 2/15 [00:02<00:15,  1.22s/it]
Loading safetensors checkpoint shards:  20% Completed | 3/15 [00:03<00:15,  1.26s/it]
Loading safetensors checkpoint shards:  27% Completed | 4/15 [00:04<00:13,  1.23s/it]
Loading safetensors checkpoint shards:  33% Completed | 5/15 [00:06<00:12,  1.20s/it]
Loading safetensors checkpoint shards:  40% Completed | 6/15 [00:07<00:10,  1.19s/it]
Loading safetensors checkpoint shards:  47% Completed | 7/15 [00:08<00:09,  1.22s/it]
Loading safetensors checkpoint shards:  53% Completed | 8/15 [00:09<00:08,  1.21s/it]
Loading safetensors checkpoint shards:  60% Completed | 9/15 [00:10<00:07,  1.20s/it]
Loading safetensors checkpoint shards:  67% Completed | 10/15 [00:12<00:05,  1.19s/it]
Loading safetensors checkpoint shards:  73% Completed | 11/15 [00:13<00:04,  1.22s/it]
Loading safetensors checkpoint shards:  80% Completed | 12/15 [00:14<00:03,  1.24s/it]
Loading safetensors checkpoint shards:  87% Completed | 13/15 [00:15<00:02,  1.26s/it]
Loading safetensors checkpoint shards:  93% Completed | 14/15 [00:17<00:01,  1.27s/it]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [00:18<00:00,  1.24s/it]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [00:18<00:00,  1.23s/it]
(EngineCore_DP0 pid=30853)

(EngineCore_DP0 pid=30853) INFO 02-17 17:36:15 [default_loader.py:291] Loading weights took 18.50 seconds
(EngineCore_DP0 pid=30853) WARNING 02-17 17:36:15 [marlin_utils_fp4.py:336] Your GPU does not have native support for FP4 computation but FP4 quantization is being used. Weight-only FP4 compression will be used leveraging the Marlin kernel. This may degrade performance for compute-heavy workloads.
(EngineCore_DP0 pid=30853) INFO 02-17 17:36:19 [gpu_model_runner.py:4130] Model loading took 65.97 GiB memory and 22.721380 seconds
(EngineCore_DP0 pid=30853) INFO 02-17 17:36:29 [backends.py:812] Using cache directory: /home/sabrina/.cache/vllm/torch_compile_cache/4d643c9beb/rank_0_0/backbone for vLLM's torch.compile
(EngineCore_DP0 pid=30853) INFO 02-17 17:36:29 [backends.py:872] Dynamo bytecode transform time: 8.94 s
(EngineCore_DP0 pid=30853) INFO 02-17 17:36:38 [backends.py:267] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 1.185 s
(EngineCore_DP0 pid=30853) INFO 02-17 17:36:38 [monitor.py:34] torch.compile takes 10.12 s in total
(EngineCore_DP0 pid=30853) INFO 02-17 17:36:39 [gpu_worker.py:356] Available KV cache memory: 3.34 GiB
(EngineCore_DP0 pid=30853) INFO 02-17 17:36:39 [kv_cache_utils.py:1307] GPU KV cache size: 48,688 tokens
(EngineCore_DP0 pid=30853) INFO 02-17 17:36:39 [kv_cache_utils.py:1312] Maximum concurrency for 120,000 tokens per request: 0.76x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 83/83 [00:08<00:00,  9.64it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:03<00:00,  9.67it/s]

(EngineCore_DP0 pid=30853) INFO 02-17 17:36:52 [gpu_model_runner.py:5063] Graph capturing finished in 13 secs, took 1.12 GiB
(EngineCore_DP0 pid=30853) INFO 02-17 17:36:52 [core.py:272] init engine (profile, create kv cache, warmup model) took 33.11 seconds
(EngineCore_DP0 pid=30853) INFO 02-17 17:36:55 [vllm.py:624] Asynchronous scheduling is enabled.
INFO 02-17 17:36:55 [llm.py:343] Supported tasks: ['generate']

Adding requests: 100%|██████████| 12/12 [00:00<00:00, 171.98it/s]
Processed prompts: 100%|██████████| 12/12 [00:26<00:00,  2.23s/it, est. speed input: 973.02 toks/s, output: 523.60 toks/s]
[rank0]:[W217 17:37:22.482126196 ProcessGroupNCCL.cpp:1524] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

##### View results

In [32]:
summaries.head()

,patient_id,cancer_history_summary,general_exclusion_criteria_evidence
0,-12,Age: 19 \nSex: Male \nCancer type: Osteosarc...,"No evidence of uncontrolled brain metastases, ..."
1,-11,Age: 68 \nSex: Male \n\nCancer type: Cutaneo...,"No evidence of uncontrolled brain metastases, ..."
2,-10,Age: 55 \nSex: Female \nCancer type: Ovarian...,"No evidence of uncontrolled brain metastases, ..."
3,-9,Age: 45 \nSex: Male \nCancer type: T‑cell ly...,- Liver dysfunction: Grade 3 transaminitis (AS...
4,-8,Age: 76 \nSex: Female \nCancer type: Ovarian...,"No evidence of uncontrolled brain metastases, ..."

Metadata contains a snapshot of the config used and metadata on the model used.

In [33]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'backend': 'local',
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'trial': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 10000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n'},
  'patient': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 120000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.2},
   'prompt_files': {'primer': 'patient.user.primer.txt',
    'question': 'patient.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n',
   'text_token_threshold': 115000,
   'tagger': {'model_name': 'ksg-dfci/TinyBertOncoTagger-1225',
    'device': 'cuda',
    'batch_size': 1024,
    'positive_tag_cutoff': 0.1,
    'negative_tag_cutoff': 0.9}},
  'embedding': {'model_path': 'ksg-dfci/TrialSpace-1225',
   'device': 'cpu',
   'prompt_file': 'embedding.txt'}},
 'model_metadata': {'model_name': 'openai/gpt-oss-120b',
  'model_sha': 'b5c939de8f754692c1647ca79fbf85e8c1e70f8a',
  'created_at': '2025-08-04T22:33:06+00:00',
  'last_modified': '2025-08-26T17:25:03+00:00'}}

Summarization step QC report

In [34]:
qc_report

                                        metric  value  percent ids
0      patients_dropped_noninformative_summary      0      0.0  []
1              patients_truncated_llm_response      0      0.0  []
2        patients_exceed_embedding_token_limit      0      0.0  []
3    patients_exclusion_criteria_not_extracted      0      0.0  []
4                 patients_missing_keyword:Age      0      0.0  []
5                 patients_missing_keyword:Sex      0      0.0  []
6         patients_missing_keyword:Cancer type      0      0.0  []
7           patients_missing_keyword:Histology      0      0.0  []
8      patients_missing_keyword:Current extent      0      0.0  []
9          patients_missing_keyword:Biomarkers      0      0.0  []
10  patients_missing_keyword:Treatment history      0      0.0  []

## Embed for matching

In [2]:
from mmai.embedding import embed_for_matching

In [3]:
# Uncomment if you want to start from previously generated summaries
trial_results = pd.read_csv("output/trial_summaries.csv")
patient_summaries = pd.read_csv("output/patient_summaries.csv", dtype="str")

### Trials

In [4]:
embedded_trials, metadata = embed_for_matching(trial_results, entity_type="trial", return_metadata=True)

/home/sabrina/mmai-package/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
embedded_trials.head()

  space_trial_id                                          embedding
0  NCT03319901-1  [-0.016687314957380295, -0.02402193658053875, ...
1  NCT03319901-2  [-0.005378431174904108, -0.022160440683364868,...
2  NCT04792489-1  [-0.013197503052651882, -0.05359682813286781, ...
3  NCT04792489-2  [-0.015272924676537514, -0.039096202701330185,...
4  NCT04792489-3  [-0.030957337468862534, -0.03065749816596508, ...

Metadata contains a snapshot of the config used and metadata on the models used.

In [6]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'backend': 'local',
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'trial': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 10000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n'},
  'patient': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 120000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.2},
   'prompt_files': {'primer': 'patient.user.primer.txt',
    'question': 'patient.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n',
   'text_token_threshold': 115000,
   'tagger': {'model_name': 'ksg-dfci/TinyBertOncoTagger-1225',
    'device': 'cuda',
    'batch_size': 1024,
    'positive_tag_cutoff': 0.1,
    'negative_tag_cutoff': 0.9}},
  'embedding': {'model_path': 'ksg-dfci/TrialSpace-1225',
   'device': 'cuda',
   'prompt_file': 'embedding.txt'},
  'reasonable_match': {'model_name': 'ksg-dfci/TrialChecker-1225',
   'device': 'cuda',
   'prompt_file': 'reasonable_match_checker_template.txt'},
  'exclusion_criteria': {'model_name': 'ksg-dfci/BoilerPlateChecker-1225',
   'device': 'cuda',
   'prompt_file': 'exclusion_criteria_checker_template.txt'}},
 'model_metadata': {'embedding_model': {'model_name': 'ksg-dfci/TrialSpace-1225',
   'model_sha': '5f6a350231ccfc56782248307f3b6599baabb481',
   'created_at': '2025-09-03T14:01:48+00:00',
   'last_modified': '2025-12-16T01:42:12+00:00'}}}

### Patients

In [7]:
embedded_patients, metadata = embed_for_matching(patient_summaries, entity_type="patient", return_metadata=True)

In [8]:
embedded_patients.head()

  patient_id                                          embedding
0        -12  [0.006629263516515493, -0.009149276651442051, ...
1        -11  [-0.0018376412335783243, -0.019815512001514435...
2        -10  [-0.005380611401051283, -0.024504821747541428,...
3         -9  [0.012340912595391273, -0.02654411271214485, -...
4         -8  [-0.011416499502956867, -0.02986742928624153, ...

Metadata contains a snapshot of the config used and metadata on the models used.

In [9]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'backend': 'local',
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'trial': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 10000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n'},
  'patient': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 120000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.2},
   'prompt_files': {'primer': 'patient.user.primer.txt',
    'question': 'patient.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n',
   'text_token_threshold': 115000,
   'tagger': {'model_name': 'ksg-dfci/TinyBertOncoTagger-1225',
    'device': 'cuda',
    'batch_size': 1024,
    'positive_tag_cutoff': 0.1,
    'negative_tag_cutoff': 0.9}},
  'embedding': {'model_path': 'ksg-dfci/TrialSpace-1225',
   'device': 'cuda',
   'prompt_file': 'embedding.txt'},
  'reasonable_match': {'model_name': 'ksg-dfci/TrialChecker-1225',
   'device': 'cuda',
   'prompt_file': 'reasonable_match_checker_template.txt'},
  'exclusion_criteria': {'model_name': 'ksg-dfci/BoilerPlateChecker-1225',
   'device': 'cuda',
   'prompt_file': 'exclusion_criteria_checker_template.txt'}},
 'model_metadata': {'embedding_model': {'model_name': 'ksg-dfci/TrialSpace-1225',
   'model_sha': '5f6a350231ccfc56782248307f3b6599baabb481',
   'created_at': '2025-09-03T14:01:48+00:00',
   'last_modified': '2025-12-16T01:42:12+00:00'}}}

## Generate candidate matches

In [10]:
from mmai.matching import generate_candidate_matches

### Patient-centric

In [11]:
patient_centric_candidate_matches = generate_candidate_matches(
    query_df=embedded_patients, corpus_df=embedded_trials
)

In [12]:
patient_centric_candidate_matches.head()

  patient_id space_trial_id  similarity_score  rank
0        -12  NCT06709495-4          0.914581     1
1        -12  NCT04851119-5          0.905763     2
2        -12  NCT05377996-1          0.851980     3
3        -12  NCT05372640-3          0.838299     4
4        -12  NCT06234423-2          0.815871     5

### Trial-centric

In [13]:
trial_centric_candidate_matches = generate_candidate_matches(
    query_df=embedded_trials, corpus_df=embedded_patients
)

In [14]:
trial_centric_candidate_matches.head()

  space_trial_id patient_id  similarity_score  rank
0  NCT03319901-1         -9          0.587195     1
1  NCT03319901-1         -7          0.541617     2
2  NCT03319901-1         -6          0.472376     3
3  NCT03319901-1         -8          0.461709     4
4  NCT03319901-1         -3          0.460745     5

## Reasonable match check

In [15]:
from mmai.matching import reasonable_match_check

### Run on patient-centric results

Add back in AI generated patient and trial space summaries using IDs, as the reasonable match check operates on these.

In [16]:
patient_centric_candidate_matches_with_context = patient_centric_candidate_matches.merge(
    patient_summaries[["patient_id", "cancer_history_summary"]],
    on="patient_id",
    how="left",
).merge(
    trial_results[["space_trial_id", "clinical_space_summary"]],
    on="space_trial_id",
    how="left",
)
patient_centric_candidate_matches_with_context.head()

,patient_id,space_trial_id,similarity_score,rank,cancer_history_summary,clinical_space_summary
0,-12,NCT06709495-4,0.914581,1,Age: 19 \nSex: Male \nCancer type: Osteosarc...,Age range allowed: 12-49 years. Sex allowed: b...
1,-12,NCT04851119-5,0.905763,2,Age: 19 \nSex: Male \nCancer type: Osteosarc...,Age range allowed: ≥ 12 months to ≤ 30 years. ...
2,-12,NCT05377996-1,0.851980,3,Age: 19 \nSex: Male \nCancer type: Osteosarc...,Age range allowed: NA. Sex allowed: both. Canc...
3,-12,NCT05372640-3,0.838299,4,Age: 19 \nSex: Male \nCancer type: Osteosarc...,Age range allowed: ≥12 years. Sex allowed: bot...
4,-12,NCT06234423-2,0.815871,5,Age: 19 \nSex: Male \nCancer type: Osteosarc...,Age range allowed: ≥18 years. Sex allowed: Mal...

Run checker.

In [17]:
patient_centric_reasonable_matches, metadata = reasonable_match_check(patient_centric_candidate_matches_with_context, return_metadata=True)

Device set to use cuda

In [18]:
patient_centric_reasonable_matches.head()

  patient_id space_trial_id  reasonable_match_score  reasonable_match
0        -12  NCT06709495-4                0.991756              True
1        -12  NCT04851119-5                0.998451              True
2        -12  NCT05377996-1                0.999859              True
3        -12  NCT05372640-3                0.999340              True
4        -12  NCT06234423-2                0.999506              True

In [19]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'backend': 'local',
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'trial': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 10000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n'},
  'patient': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 120000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.2},
   'prompt_files': {'primer': 'patient.user.primer.txt',
    'question': 'patient.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n',
   'text_token_threshold': 115000,
   'tagger': {'model_name': 'ksg-dfci/TinyBertOncoTagger-1225',
    'device': 'cuda',
    'batch_size': 1024,
    'positive_tag_cutoff': 0.1,
    'negative_tag_cutoff': 0.9}},
  'embedding': {'model_path': 'ksg-dfci/TrialSpace-1225',
   'device': 'cuda',
   'prompt_file': 'embedding.txt'},
  'reasonable_match': {'model_name': 'ksg-dfci/TrialChecker-1225',
   'device': 'cuda',
   'prompt_file': 'reasonable_match_checker_template.txt'},
  'exclusion_criteria': {'model_name': 'ksg-dfci/BoilerPlateChecker-1225',
   'device': 'cuda',
   'prompt_file': 'exclusion_criteria_checker_template.txt'}},
 'model_metadata': {'reasonable_match_checker': {'model_name': 'ksg-dfci/TrialChecker-1225',
   'model_sha': '27926b4bfaff8e4f6ba178e923bc9d6032fffab2',
   'created_at': '2025-09-03T14:09:37+00:00',
   'last_modified': '2025-12-16T00:25:50+00:00'}}}

### Run on trial-centric results

Add back in AI generated patient and trial space summaries using IDs, as the reasonable match check operates on these.

In [20]:
trial_centric_candidate_matches_with_context = trial_centric_candidate_matches.merge(
    patient_summaries[["patient_id", "cancer_history_summary"]],
    on="patient_id",
    how="left",
).merge(
    trial_results[["space_trial_id", "clinical_space_summary"]],
    on="space_trial_id",
    how="left",
)
trial_centric_candidate_matches_with_context.head()

,space_trial_id,patient_id,similarity_score,rank,cancer_history_summary,clinical_space_summary
0,NCT03319901-1,-9,0.587195,1,Age: 45 \nSex: Male \n\nCancer type: T‑cell ...,Age range allowed: ≥60 years. Sex allowed: Any...
1,NCT03319901-1,-7,0.541617,2,Age: 70 \nSex: Male \nCancer type: Prostate ...,Age range allowed: ≥60 years. Sex allowed: Any...
2,NCT03319901-1,-6,0.472376,3,Age: 63 \nSex: Unspecified \nCancer type: Sm...,Age range allowed: ≥60 years. Sex allowed: Any...
3,NCT03319901-1,-8,0.461709,4,Age: 76 \nSex: Female \nCancer type: Ovarian...,Age range allowed: ≥60 years. Sex allowed: Any...
4,NCT03319901-1,-3,0.460745,5,Age: 66 \nSex: Male \nCancer type: Breast ca...,Age range allowed: ≥60 years. Sex allowed: Any...

Run checker.

In [21]:
trial_centric_reasonable_matches, metadata = reasonable_match_check(trial_centric_candidate_matches_with_context.iloc[0:240,], return_metadata=True)

Device set to use cuda

In [22]:
trial_centric_reasonable_matches.head()

  patient_id space_trial_id  reasonable_match_score  reasonable_match
0        -10  NCT06234423-1                0.998354              True
1        -12  NCT06234423-2                0.999506              True
2        -11  NCT06234423-2                0.998947              True
3         -4  NCT06234423-2                0.966271              True
4         -3  NCT06234423-2                0.996109              True

In [23]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'backend': 'local',
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'trial': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 10000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n'},
  'patient': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 120000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.2},
   'prompt_files': {'primer': 'patient.user.primer.txt',
    'question': 'patient.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n',
   'text_token_threshold': 115000,
   'tagger': {'model_name': 'ksg-dfci/TinyBertOncoTagger-1225',
    'device': 'cuda',
    'batch_size': 1024,
    'positive_tag_cutoff': 0.1,
    'negative_tag_cutoff': 0.9}},
  'embedding': {'model_path': 'ksg-dfci/TrialSpace-1225',
   'device': 'cuda',
   'prompt_file': 'embedding.txt'},
  'reasonable_match': {'model_name': 'ksg-dfci/TrialChecker-1225',
   'device': 'cuda',
   'prompt_file': 'reasonable_match_checker_template.txt'},
  'exclusion_criteria': {'model_name': 'ksg-dfci/BoilerPlateChecker-1225',
   'device': 'cuda',
   'prompt_file': 'exclusion_criteria_checker_template.txt'}},
 'model_metadata': {'reasonable_match_checker': {'model_name': 'ksg-dfci/TrialChecker-1225',
   'model_sha': '27926b4bfaff8e4f6ba178e923bc9d6032fffab2',
   'created_at': '2025-09-03T14:09:37+00:00',
   'last_modified': '2025-12-16T00:25:50+00:00'}}}

## Exclusion criteria check

### Run on patient-centric results

In [24]:
# limit to unique patient-trial ID pairs
patient_centric_reasonable_matches['trial_id'] = patient_centric_reasonable_matches['space_trial_id'].str.split('-').str[0]
unique_patient_trial_pairs = patient_centric_reasonable_matches[['patient_id', 'trial_id']].drop_duplicates()

# add in exclusion criteria for patients and trials
patient_trial_pairs_with_exclusion_context = unique_patient_trial_pairs.merge(
    patient_summaries[["patient_id", "general_exclusion_criteria_evidence"]],
    on="patient_id",
    how="left",
).merge(
    trial_results[["trial_id", "general_exclusion_criteria"]].drop_duplicates(),
    on="trial_id",
    how="left",
)
patient_trial_pairs_with_exclusion_context.head()

,patient_id,trial_id,general_exclusion_criteria_evidence,general_exclusion_criteria
0,-12,NCT06709495,"No evidence of uncontrolled brain metastases, ...",History of severe or unresolved pneumonia/pneu...
1,-12,NCT04851119,"No evidence of uncontrolled brain metastases, ...",Pregnancy or breastfeeding; inadequate contrac...
2,-12,NCT05377996,"No evidence of uncontrolled brain metastases, ...",Major surgical procedure performed within 28 d...
3,-12,NCT05372640,"No evidence of uncontrolled brain metastases, ...",Patients with uncontrolled intercurrent illnes...
4,-12,NCT06234423,"No evidence of uncontrolled brain metastases, ...",Active or progressing brain metastases or lept...

In [26]:
from mmai.matching import exclusion_criteria_check

# run exclusion criteria check
exclusion_results, metadata = exclusion_criteria_check(patient_trial_pairs_with_exclusion_context, return_metadata = True)
exclusion_results.head()

Device set to use cuda

  patient_id     trial_id  exclusion_score  exclusion_criteria_pass
0        -12  NCT06709495         0.999972                     True
1        -12  NCT04851119         0.999988                     True
2        -12  NCT05377996         0.999983                     True
3        -12  NCT05372640         0.999993                     True
4        -12  NCT06234423         0.999957                     True

In [27]:
exclusion_results['exclusion_criteria_pass'].value_counts()

exclusion_criteria_pass
True     145
False      6
Name: count, dtype: int64

In [28]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'backend': 'local',
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'trial': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 10000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n'},
  'patient': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 120000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.2},
   'prompt_files': {'primer': 'patient.user.primer.txt',
    'question': 'patient.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n',
   'text_token_threshold': 115000,
   'tagger': {'model_name': 'ksg-dfci/TinyBertOncoTagger-1225',
    'device': 'cuda',
    'batch_size': 1024,
    'positive_tag_cutoff': 0.1,
    'negative_tag_cutoff': 0.9}},
  'embedding': {'model_path': 'ksg-dfci/TrialSpace-1225',
   'device': 'cuda',
   'prompt_file': 'embedding.txt'},
  'reasonable_match': {'model_name': 'ksg-dfci/TrialChecker-1225',
   'device': 'cuda',
   'prompt_file': 'reasonable_match_checker_template.txt'},
  'exclusion_criteria': {'model_name': 'ksg-dfci/BoilerPlateChecker-1225',
   'device': 'cuda',
   'prompt_file': 'exclusion_criteria_checker_template.txt'}},
 'model_metadata': {'exclusion_criteria_checker': {'model_name': 'ksg-dfci/BoilerPlateChecker-1225',
   'model_sha': '291b27a65830aa43e13924c84e9e7f5f08e4e900',
   'created_at': '2025-09-03T14:11:00+00:00',
   'last_modified': '2025-12-20T18:46:15+00:00'}}}

### Run on trial-centric results

In [29]:
# limit to unique trial-patient ID pairs
trial_centric_reasonable_matches["trial_id"] = (
    trial_centric_reasonable_matches["space_trial_id"].str.split("-").str[0]
)

unique_trial_patient_pairs = (
    trial_centric_reasonable_matches[["trial_id", "patient_id"]]
    .drop_duplicates()
)

# add in exclusion criteria for trials and patients
trial_patient_pairs_with_exclusion_context = (
    unique_trial_patient_pairs
    .merge(
        trial_results[["trial_id", "general_exclusion_criteria"]].drop_duplicates(),
        on="trial_id",
        how="left",
    )
    .merge(
        patient_summaries[["patient_id", "general_exclusion_criteria_evidence"]],
        on="patient_id",
        how="left",
    )
)
trial_patient_pairs_with_exclusion_context.head()

,trial_id,patient_id,general_exclusion_criteria,general_exclusion_criteria_evidence
0,NCT06234423,-10,Active or progressing brain metastases or lept...,"No evidence of uncontrolled brain metastases, ..."
1,NCT06234423,-12,Active or progressing brain metastases or lept...,"No evidence of uncontrolled brain metastases, ..."
2,NCT06234423,-11,Active or progressing brain metastases or lept...,"No evidence of uncontrolled brain metastases, ..."
3,NCT06234423,-4,Active or progressing brain metastases or lept...,Evidence of renal dysfunction – grade 3 protei...
4,NCT06234423,-3,Active or progressing brain metastases or lept...,"No evidence of uncontrolled brain metastases, ..."

In [30]:
# run exclusion criteria check
exclusion_results, exclusion_metadata = exclusion_criteria_check(
    trial_patient_pairs_with_exclusion_context,
    return_metadata=True,
)
exclusion_results.head()

Device set to use cuda

  patient_id     trial_id  exclusion_score  exclusion_criteria_pass
0        -10  NCT06234423         0.999994                     True
1        -12  NCT06234423         0.999957                     True
2        -11  NCT06234423         0.999994                     True
3         -4  NCT06234423         0.710231                     True
4         -3  NCT06234423         0.999989                     True

In [31]:
exclusion_results["exclusion_criteria_pass"].value_counts()

exclusion_criteria_pass
True    25
Name: count, dtype: int64

In [32]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'backend': 'local',
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'trial': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 10000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n'},
  'patient': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 120000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7500,
    'repetition_penalty': 1.2},
   'prompt_files': {'primer': 'patient.user.primer.txt',
    'question': 'patient.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': '\\n.*Boilerplate.*\\n',
   'text_token_threshold': 115000,
   'tagger': {'model_name': 'ksg-dfci/TinyBertOncoTagger-1225',
    'device': 'cuda',
    'batch_size': 1024,
    'positive_tag_cutoff': 0.1,
    'negative_tag_cutoff': 0.9}},
  'embedding': {'model_path': 'ksg-dfci/TrialSpace-1225',
   'device': 'cuda',
   'prompt_file': 'embedding.txt'},
  'reasonable_match': {'model_name': 'ksg-dfci/TrialChecker-1225',
   'device': 'cuda',
   'prompt_file': 'reasonable_match_checker_template.txt'},
  'exclusion_criteria': {'model_name': 'ksg-dfci/BoilerPlateChecker-1225',
   'device': 'cuda',
   'prompt_file': 'exclusion_criteria_checker_template.txt'}},
 'model_metadata': {'exclusion_criteria_checker': {'model_name': 'ksg-dfci/BoilerPlateChecker-1225',
   'model_sha': '291b27a65830aa43e13924c84e9e7f5f08e4e900',
   'created_at': '2025-09-03T14:11:00+00:00',
   'last_modified': '2025-12-20T18:46:15+00:00'}}}